pvz_columnslist=['Protosswin', 'Protoss_mineral_collection_rate', 'Protoss_gas_collection_rate', 'Protoss_unspent_minerals', 'Protoss_unspent_gas', 'Zerg_mineral_collection_rate', 
'Zerg_gas_collection_rate', 'Zerg_unspent_minerals', 'Zerg_unspent_gas', 'loop', 'Probe_live', 'Probe_dead', 'Probe_in_progress', 'Nexus_live', 'Nexus_dead', 'Nexus_in_progress', 
'Egg_live', 'Egg_dead', 'Egg_in_progress', 'Larva_live', 'Larva_dead', 'Larva_in_progress', 'Drone_live', 'Drone_dead', 'Drone_in_progress', 'Overlord_live', 'Overlord_dead', 
'Overlord_in_progress', 'Hatchery_live', 'Hatchery_dead', 'Hatchery_in_progress', 'Pylon_live', 'Pylon_dead', 'Pylon_in_progress', 'Gateway_live', 'Gateway_dead', 
'Gateway_in_progress', 'Assimilator_live', 'Assimilator_dead', 'Assimilator_in_progress', 'Extractor_live', 'Extractor_dead', 'Extractor_in_progress', 'SpawningPool_live', 
'SpawningPool_dead', 'SpawningPool_in_progress', 'CyberneticsCore_live', 'CyberneticsCore_dead', 'CyberneticsCore_in_progress', 'Adept_live', 'Adept_dead', 'Adept_in_progress', 
'Stargate_live', 'Stargate_dead', 'Stargate_in_progress', 'Queen_live', 'Queen_dead', 'Queen_in_progress', 'Zergling_live', 'Zergling_dead', 'Zergling_in_progress', 
'CreepTumorQueen_live', 'CreepTumorQueen_dead', 'CreepTumorQueen_in_progress', 'CreepTumorBurrowed_live', 'CreepTumorBurrowed_dead', 'CreepTumorBurrowed_in_progress', 
'EvolutionChamber_live', 'EvolutionChamber_dead', 'EvolutionChamber_in_progress', 'ZerglingMovementSpeed', 'Phoenix_live', 'Phoenix_dead', 'Phoenix_in_progress', 
'SporeCrawler_live', 'SporeCrawler_dead', 'SporeCrawler_in_progress', 'Oracle_live', 'Oracle_dead', 'Oracle_in_progress', 'WarpGateResearch', 'WarpGate_live', 
'WarpGate_dead', 'WarpGate_in_progress', 'RoboticsFacility_live', 'RoboticsFacility_dead', 'RoboticsFacility_in_progress', 'BanelingNest_live', 'BanelingNest_dead', 
'BanelingNest_in_progress', 'CreepTumor_live', 'CreepTumor_dead', 'CreepTumor_in_progress', 'TwilightCouncil_live', 'TwilightCouncil_dead', 'TwilightCouncil_in_progress', 
'Forge_live', 'Forge_dead', 'Forge_in_progress', 'Sentry_live', 'Sentry_dead', 'Sentry_in_progress', 'Zealot_live', 'Zealot_dead', 'Zealot_in_progress', 'ZergMeleeWeaponsLevel1', 
'BanelingCocoon_live', 'BanelingCocoon_dead', 'BanelingCocoon_in_progress', 'WarpPrism_live', 'WarpPrism_dead', 'WarpPrism_in_progress', 'Stalker_live', 'Stalker_dead', 
'Stalker_in_progress', 'Lair_live', 'Lair_dead', 'Lair_in_progress', 'HighTemplar_live', 'HighTemplar_dead', 'HighTemplar_in_progress', 'Baneling_live', 'Baneling_dead', 
'Baneling_in_progress', 'HydraliskDen_live', 'HydraliskDen_dead', 'HydraliskDen_in_progress', 'Archon_live', 'Archon_dead', 'Archon_in_progress', 'Observer_live', 'Observer_dead', 
'Observer_in_progress', 'ShieldBattery_live', 'ShieldBattery_dead', 'ShieldBattery_in_progress', 'WarpPrismPhasing_live', 'WarpPrismPhasing_dead', 'WarpPrismPhasing_in_progress', 
'Charge', 'Immortal_live', 'Immortal_dead', 'Immortal_in_progress', 'ProtossGroundWeaponsLevel1', 'Hydralisk_live', 'Hydralisk_dead', 'Hydralisk_in_progress', 'OverlordCocoon_live', 
'OverlordCocoon_dead', 'OverlordCocoon_in_progress', 'Overseer_live', 'Overseer_dead', 'Overseer_in_progress', 'EvolveMuscularAugments', 'CentrificalHooks', 
'ZergMeleeWeaponsLevel2', 'ObserverSiegeMode_live', 'ObserverSiegeMode_dead', 'ObserverSiegeMode_in_progress', 'PhotonCannon_live', 'PhotonCannon_dead', 'PhotonCannon_in_progress', 
'EvolveGroovedSpines', 'PsiStormTech', 'ProtossGroundWeaponsLevel2', 'RoachWarren_live', 'RoachWarren_dead', 'RoachWarren_in_progress', 'Roach_live', 'Roach_dead', 
'Roach_in_progress', 'AdeptPiercingAttack', 'DarkShrine_live', 'DarkShrine_dead', 'DarkShrine_in_progress', 'RavagerCocoon_live', 'RavagerCocoon_dead', 'RavagerCocoon_in_progress', 
'Ravager_live', 'Ravager_dead', 'Ravager_in_progress', 'Spire_live', 'Spire_dead', 'Spire_in_progress', 'GlialReconstitution', 'DarkTemplar_live', 'DarkTemplar_dead', 
'DarkTemplar_in_progress', 'Mutalisk_live', 'Mutalisk_dead', 'Mutalisk_in_progress', 'Colossus_live', 'Colossus_dead', 'Colossus_in_progress', 'ZergFlyerWeaponsLevel1', 
'ZergMissileWeaponsLevel1', 'InfestationPit_live', 'InfestationPit_dead', 'InfestationPit_in_progress', 'ZergMissileWeaponsLevel2', 'SwarmHostMP_live', 'SwarmHostMP_dead', 
'SwarmHostMP_in_progress', 'Broodling_live', 'Broodling_dead', 'Broodling_in_progress', 'LocustMPFlying_live', 'LocustMPFlying_dead', 'LocustMPFlying_in_progress', 
'LocustMP_live', 'LocustMP_dead', 'LocustMP_in_progress', 'LocustMPPrecursor_live', 'LocustMPPrecursor_dead', 'LocustMPPrecursor_in_progress', 'TransportOverlordCocoon_live', 
'TransportOverlordCocoon_dead', 'TransportOverlordCocoon_in_progress', 'OverlordTransport_live', 'OverlordTransport_dead', 'OverlordTransport_in_progress', 'SpineCrawler_live', 
'SpineCrawler_dead', 'SpineCrawler_in_progress', 'Hive_live', 'Hive_dead', 'Hive_in_progress', 'ZerglingAttackSpeed', 'OverseerSiegeMode_live', 'OverseerSiegeMode_dead', 
'OverseerSiegeMode_in_progress', 'GreaterSpire_live', 'GreaterSpire_dead', 'GreaterSpire_in_progress', 'ProtossGroundWeaponsLevel3', 'FleetBeacon_live', 'FleetBeacon_dead', 
'FleetBeacon_in_progress', 'BlinkTech', 'LurkerDenMP_live', 'LurkerDenMP_dead', 'LurkerDenMP_in_progress', 'LurkerMPEgg_live', 'LurkerMPEgg_dead', 'LurkerMPEgg_in_progress', 
'LurkerMP_live', 'LurkerMP_dead', 'LurkerMP_in_progress', 'LurkerMPBurrowed_live', 'LurkerMPBurrowed_dead', 'LurkerMPBurrowed_in_progress', 'VoidRay_live', 'VoidRay_dead', 
'VoidRay_in_progress', 'OverlordSpeed', 'ZergGroundArmorsLevel1', 'ProtossShieldsLevel1', 'Corruptor_live', 'Corruptor_dead', 'Corruptor_in_progress', 'BroodLordCocoon_live', 
'BroodLordCocoon_dead', 'BroodLordCocoon_in_progress', 'BroodLord_live', 'BroodLord_dead', 'BroodLord_in_progress', 'BroodlingEscort_live', 'BroodlingEscort_dead', 
'BroodlingEscort_in_progress', 'ProtossAirWeaponsLevel1', 'NydusNetwork_live', 'NydusNetwork_dead', 'NydusNetwork_in_progress', 'NydusCanal_live', 'NydusCanal_dead', 
'NydusCanal_in_progress', 'Burrow', 'RoboticsBay_live', 'RoboticsBay_dead', 'RoboticsBay_in_progress', 'ExtendedThermalLance', 'InfestorEnergyUpgrade', 'Mothership_live', 
'Mothership_dead', 'Mothership_in_progress', 'DiggingClaws', 'ZergMissileWeaponsLevel3', 'Tempest_live', 'Tempest_dead', 'Tempest_in_progress', 'ZergFlyerWeaponsLevel2', 
'ZergGroundArmorsLevel2', 'ProtossGroundArmorsLevel1', 'ProtossGroundArmorsLevel2', 'Infestor_live', 'Infestor_dead', 'Infestor_in_progress', 'NeuralParasite', 'Carrier_live', 
'Carrier_dead', 'Carrier_in_progress', 'Interceptor_live', 'Interceptor_dead', 'Interceptor_in_progress', 'ZergMeleeWeaponsLevel3', 'ZergFlyerArmorsLevel1', 'UltraliskCavern_live', 
'UltraliskCavern_dead', 'UltraliskCavern_in_progress', 'ProtossAirArmorsLevel1', 'ProtossAirWeaponsLevel2', 'ProtossShieldsLevel2', 'Disruptor_live', 'Disruptor_dead', 
'Disruptor_in_progress', 'ObserverGraviticBooster', 'ChitinousPlating', 'ZergFlyerArmorsLevel2', 'ProtossAirWeaponsLevel3', 'GraviticDrive', 'ProtossAirArmorsLevel2', 
'ProtossShieldsLevel3', 'ZergFlyerWeaponsLevel3', 'ZergFlyerArmorsLevel3', 'ZergGroundArmorsLevel3', 'ProtossAirArmorsLevel3', 'Ultralisk_live', 'Ultralisk_dead', 
'Ultralisk_in_progress', 'InfestedTerransEgg_live', 'InfestedTerransEgg_dead', 'InfestedTerransEgg_in_progress', 'InfestorTerran_live', 'InfestorTerran_dead', 
'InfestorTerran_in_progress', 'Viper_live', 'Viper_dead', 'Viper_in_progress', 'ProtossGroundArmorsLevel3', 'PhoenixRangeUpgrade', 'DarkTemplarBlinkUpgrade', 
'TunnelingClaws', 'LurkerRange', 'MicrobialShroud', 'AnabolicSynthesis']