pvp = ['player_1_Protoss_mineral_collection_rate', 
       'player_1_Protoss_gas_collection_rate', 
       'player_1_Protoss_unspent_minerals', 
       'player_1_Protoss_unspent_gas', 
       'player_2_Protoss_mineral_collection_rate', 
       'player_2_Protoss_gas_collection_rate', 
       'player_2_Protoss_unspent_minerals', 
       'player_2_Protoss_unspent_gas', 
       'result', 
       'loop', 
       'player_1_Probe_live', 
       'player_1_Probe_dead', 
       'player_1_Probe_in_progress', 
       'player_1_Nexus_live', 
       'player_1_Nexus_dead', 
       'player_1_Nexus_in_progress', 
       'player_2_Probe_live', 
       'player_2_Probe_dead', 
       'player_2_Probe_in_progress', 
       'player_2_Nexus_live', 
       'player_2_Nexus_dead', 
       'player_2_Nexus_in_progress', 
       'player_1_Pylon_live', 
       'player_1_Pylon_dead', 
       'player_1_Pylon_in_progress', 
       'player_2_Pylon_live', 
       'player_2_Pylon_dead', 
       'player_2_Pylon_in_progress', 
       'player_1_Gateway_live', 'player_1_Gateway_dead', 'player_1_Gateway_in_progress', 
       'player_2_Gateway_live', 'player_2_Gateway_dead', 'player_2_Gateway_in_progress', 
       'player_1_Assimilator_live', 'player_1_Assimilator_dead', 'player_1_Assimilator_in_progress', 
       'player_2_Assimilator_live', 'player_2_Assimilator_dead', 'player_2_Assimilator_in_progress', 
       'player_1_CyberneticsCore_live', 'player_1_CyberneticsCore_dead', 'player_1_CyberneticsCore_in_progress', 
       'player_2_CyberneticsCore_live', 'player_2_CyberneticsCore_dead', 'player_2_CyberneticsCore_in_progress', 
       'player_1_Sentry_live', 'player_1_Sentry_dead', 'player_1_Sentry_in_progress', 
       'player_1_Stalker_live', 'player_1_Stalker_dead', 'player_1_Stalker_in_progress', 
       'player_2_Stalker_live', 'player_2_Stalker_dead', 'player_2_Stalker_in_progress', 
       'player_1_Phoenix_live', 'player_1_Phoenix_dead', 'player_1_Phoenix_in_progress', 
       'player_2_ShieldBattery_live', 'player_2_ShieldBattery_dead', 'player_2_ShieldBattery_in_progress', 
       'player_1_TwilightCouncil_live', 'player_1_TwilightCouncil_dead', 'player_1_TwilightCouncil_in_progress', 
       'player_1_RoboticsFacility_live', 'player_1_RoboticsFacility_dead', 'player_1_RoboticsFacility_in_progress', 
       'player_2_WarpGateResearch', 'player_1_WarpGateResearch', 
       'player_2_WarpGate_live', 'player_2_WarpGate_dead', 'player_2_WarpGate_in_progress', 
       'player_1_Zealot_live', 'player_1_Zealot_dead', 'player_1_Zealot_in_progress', 
       'player_1_WarpGate_live', 'player_1_WarpGate_dead', 'player_1_WarpGate_in_progress', 
       'player_1_ShieldBattery_live', 'player_1_ShieldBattery_dead', 'player_1_ShieldBattery_in_progress', 
       'player_2_Sentry_live', 'player_2_Sentry_dead', 'player_2_Sentry_in_progress', 
       'player_1_Immortal_live', 'player_1_Immortal_dead', 'player_1_Immortal_in_progress', 
       'player_1_Adept_live', 'player_1_Adept_dead', 'player_1_Adept_in_progress', 
       'player_2_Zealot_live', 'player_2_Zealot_dead', 'player_2_Zealot_in_progress', 
       'player_1_WarpPrism_live', 'player_1_WarpPrism_dead', 'player_1_WarpPrism_in_progress', 
       'player_1_Observer_live', 'player_1_Observer_dead', 'player_1_Observer_in_progress', 
       'player_2_Adept_live', 'player_2_Adept_dead', 'player_2_Adept_in_progress', 'player_2_Stargate_live', 
       'player_2_Stargate_dead', 'player_2_Stargate_in_progress', 'player_2_RoboticsFacility_live', 
       'player_2_RoboticsFacility_dead', 'player_2_RoboticsFacility_in_progress', 'player_1_WarpPrismPhasing_live', 
       'player_1_WarpPrismPhasing_dead', 'player_1_WarpPrismPhasing_in_progress', 
       'player_1_Forge_live', 'player_1_Forge_dead', 'player_1_Forge_in_progress', 
       'player_2_Phoenix_live', 'player_2_Phoenix_dead', 'player_2_Phoenix_in_progress', 
       'player_2_Observer_live', 'player_2_Observer_dead', 'player_2_Observer_in_progress', 
       'player_2_RoboticsBay_live', 'player_2_RoboticsBay_dead', 'player_2_RoboticsBay_in_progress', 
       'player_2_Immortal_live', 'player_2_Immortal_dead', 'player_2_Immortal_in_progress', 
       'player_2_ObserverSiegeMode_live', 'player_2_ObserverSiegeMode_dead', 'player_2_ObserverSiegeMode_in_progress', 
       'player_1_PhotonCannon_live', 'player_1_PhotonCannon_dead', 'player_1_PhotonCannon_in_progress', 
       'player_1_BlinkTech', 'player_2_Oracle_live', 'player_2_Oracle_dead', 'player_2_Oracle_in_progress', 
       'player_2_Disruptor_live', 'player_2_Disruptor_dead', 'player_2_Disruptor_in_progress', 
       'player_1_ObserverSiegeMode_live', 'player_1_ObserverSiegeMode_dead', 'player_1_ObserverSiegeMode_in_progress', 
       'player_1_ProtossGroundWeaponsLevel1', 'player_1_Stargate_live', 'player_1_Stargate_dead', 
       'player_1_Stargate_in_progress', 'player_2_TwilightCouncil_live', 'player_2_TwilightCouncil_dead', 
       'player_2_TwilightCouncil_in_progress', 'player_1_Oracle_live', 'player_1_Oracle_dead', 
       'player_1_Oracle_in_progress', 'player_1_DarkShrine_live', 'player_1_DarkShrine_dead', 
       'player_1_DarkShrine_in_progress', 'player_1_DarkTemplar_live', 'player_1_DarkTemplar_dead', 
       'player_1_DarkTemplar_in_progress', 'player_2_BlinkTech', 'player_2_WarpPrism_live', 
       'player_2_WarpPrism_dead', 'player_2_WarpPrism_in_progress', 'player_2_WarpPrismPhasing_live', 
       'player_2_WarpPrismPhasing_dead', 'player_2_WarpPrismPhasing_in_progress', 
       'player_2_Forge_live', 'player_2_Forge_dead', 'player_2_Forge_in_progress', 
       'player_1_Charge', 
       'player_1_RoboticsBay_live', 'player_1_RoboticsBay_dead', 'player_1_RoboticsBay_in_progress', 
       'player_2_HighTemplar_live', 'player_2_HighTemplar_dead', 'player_2_HighTemplar_in_progress', 
       'player_2_PhotonCannon_live', 'player_2_PhotonCannon_dead', 'player_2_PhotonCannon_in_progress', 
       'player_1_HighTemplar_live', 'player_1_HighTemplar_dead', 'player_1_HighTemplar_in_progress', 
       'player_2_Archon_live', 'player_2_Archon_dead', 'player_2_Archon_in_progress', 
       'player_1_Archon_live', 'player_1_Archon_dead', 'player_1_Archon_in_progress', 
       'player_2_ProtossGroundWeaponsLevel1', 
       'player_2_Charge', 
       'player_1_Disruptor_live', 'player_1_Disruptor_dead', 'player_1_Disruptor_in_progress', 
       'player_1_ProtossGroundWeaponsLevel2', 
       'player_2_DarkShrine_live', 
       'player_2_DarkShrine_dead', 
       'player_2_DarkShrine_in_progress', 
       'player_2_ProtossGroundWeaponsLevel2', 
       'player_1_Colossus_live', 'player_1_Colossus_dead', 'player_1_Colossus_in_progress', 
       'player_2_DarkTemplar_live', 'player_2_DarkTemplar_dead', 'player_2_DarkTemplar_in_progress', 
       'player_1_ProtossGroundWeaponsLevel3', 
       'player_2_DarkTemplarBlinkUpgrade', 
       'player_2_ProtossGroundWeaponsLevel3', 
       'player_1_AdeptPiercingAttack', 
       'player_2_ProtossShieldsLevel1', 
       'player_1_ProtossShieldsLevel1', 
       'player_1_ObserverGraviticBooster', 
       'player_2_ProtossShieldsLevel2', 
       'player_2_ObserverGraviticBooster', 
       'player_2_GraviticDrive', 
       'player_1_ProtossGroundArmorsLevel1', 
       'player_1_DarkTemplarBlinkUpgrade', 
       'player_2_ProtossGroundArmorsLevel1', 
       'player_1_GraviticDrive', 
       'player_1_ProtossAirWeaponsLevel1', 
       'player_2_AdeptPiercingAttack',
       'player_2_FleetBeacon_live', 'player_2_FleetBeacon_dead', 'player_2_FleetBeacon_in_progress', 
       'player_1_FleetBeacon_live', 'player_1_FleetBeacon_dead', 'player_1_FleetBeacon_in_progress', 
       'player_2_Tempest_live', 'player_2_Tempest_dead', 'player_2_Tempest_in_progress', 
       'player_2_ProtossAirWeaponsLevel1', 
       'player_1_Carrier_live', 'player_1_Carrier_dead', 'player_1_Carrier_in_progress', 
       'player_1_Interceptor_live', 'player_1_Interceptor_dead', 'player_1_Interceptor_in_progress', 
       'player_1_Tempest_live', 'player_1_Tempest_dead', 'player_1_Tempest_in_progress', 
       'player_2_ProtossAirWeaponsLevel2', 
       'player_1_ProtossAirWeaponsLevel2', 
       'player_2_Mothership_live', 
       'player_2_Mothership_dead', 
       'player_2_Mothership_in_progress', 
       'player_2_ProtossAirWeaponsLevel3', 
       'player_2_Carrier_live', 
       'player_2_Carrier_dead', 
       'player_2_Carrier_in_progress', 
       'player_2_Interceptor_live', 
       'player_2_Interceptor_dead', 
       'player_2_Interceptor_in_progress', 
       'player_1_ProtossGroundArmorsLevel2', 
       'player_2_Colossus_live', 'player_2_Colossus_dead', 'player_2_Colossus_in_progress', 
       'player_1_VoidRay_live', 'player_1_VoidRay_dead', 'player_1_VoidRay_in_progress', 
       'player_2_ProtossGroundArmorsLevel2', 
       'player_1_ProtossShieldsLevel2', 
       'player_1_ProtossAirWeaponsLevel3', 
       'player_1_ProtossShieldsLevel3', 
       'player_1_ProtossAirArmorsLevel1', 
       'player_2_VoidRay_live', 'player_2_VoidRay_dead', 'player_2_VoidRay_in_progress', 
       'player_2_ProtossGroundArmorsLevel3',
       'player_1_Mothership_live', 'player_1_Mothership_dead', 'player_1_Mothership_in_progress', 
       'player_2_ProtossAirArmorsLevel1', 
       'player_1_ProtossAirArmorsLevel2', 
       'player_2_ProtossAirArmorsLevel2', 
       'player_2_ProtossShieldsLevel3', 
       'player_1_ProtossAirArmorsLevel3', 
       'player_2_ProtossAirArmorsLevel3',  
       'player_2_PhoenixRangeUpgrade', 
       'player_1_ExtendedThermalLance', 
       'player_1_ProtossGroundArmorsLevel3', 
       'player_2_ExtendedThermalLance', 
       'player_1_PhoenixRangeUpgrade']

pvt = ['Protoss_mineral_collection_rate', 'Protoss_gas_collection_rate', 
       'Protoss_unspent_minerals', 'Protoss_unspent_gas', 
       'Terran_mineral_collection_rate', 'Terran_gas_collection_rate', 
       'Terran_unspent_minerals', 'Terran_unspent_gas', 
       'result', 
       'loop', 
       'Probe_live', 'Probe_dead', 'Probe_in_progress', 
       'Nexus_live', 'Nexus_dead', 'Nexus_in_progress', 
       'SCV_live', 'SCV_dead', 'SCV_in_progress', 
       'CommandCenter_live', 'CommandCenter_dead', 'CommandCenter_in_progress', 
       'Pylon_live', 'Pylon_dead', 'Pylon_in_progress', 
       'SupplyDepot_live', 'SupplyDepot_dead', 'SupplyDepot_in_progress', 
       'Refinery_live', 'Refinery_dead', 'Refinery_in_progress', 
       'Gateway_live', 'Gateway_dead', 'Gateway_in_progress', 
       'Assimilator_live', 'Assimilator_dead', 'Assimilator_in_progress', 
       'Barracks_live', 'Barracks_dead', 'Barracks_in_progress', 
       'CyberneticsCore_live', 'CyberneticsCore_dead', 'CyberneticsCore_in_progress', 
       'OrbitalCommand_live', 'OrbitalCommand_dead', 'OrbitalCommand_in_progress', 
       'Factory_live', 'Factory_dead', 'Factory_in_progress', 
       'MULE_live', 'MULE_dead', 'MULE_in_progress', 
       'SupplyDepotLowered_live', 'SupplyDepotLowered_dead', 'SupplyDepotLowered_in_progress', 
       'Reaper_live', 'Reaper_dead', 'Reaper_in_progress', 
       'BarracksReactor_live', 'BarracksReactor_dead', 'BarracksReactor_in_progress', 
       'Adept_live', 'Adept_dead', 'Adept_in_progress', 
       'TwilightCouncil_live', 'TwilightCouncil_dead', 'TwilightCouncil_in_progress', 
       'FactoryTechLab_live', 'FactoryTechLab_dead', 'FactoryTechLab_in_progress', 
       'Starport_live', 'Starport_dead', 'Starport_in_progress', 
       'Stalker_live', 'Stalker_dead', 'Stalker_in_progress', 
       'Marine_live', 'Marine_dead', 'Marine_in_progress', 
       'DarkShrine_live', 'DarkShrine_dead', 'DarkShrine_in_progress', 
       'WarpGateResearch', 
       'Cyclone_live', 'Cyclone_dead', 'Cyclone_in_progress', 
       'WarpGate_live', 'WarpGate_dead', 'WarpGate_in_progress', 
       'OrbitalCommandFlying_live', 'OrbitalCommandFlying_dead', 'OrbitalCommandFlying_in_progress', 
       'Medivac_live', 'Medivac_dead', 'Medivac_in_progress', 
       'RoboticsFacility_live', 'RoboticsFacility_dead', 'RoboticsFacility_in_progress', 
       'StarportTechLab_live', 'StarportTechLab_dead', 'StarportTechLab_in_progress', 
       'ShieldBattery_live', 'ShieldBattery_dead', 'ShieldBattery_in_progress', 
       'DarkTemplar_live', 'DarkTemplar_dead', 'DarkTemplar_in_progress', 
       'EngineeringBay_live', 'EngineeringBay_dead', 'EngineeringBay_in_progress', 
       'SiegeTank_live', 'SiegeTank_dead', 'SiegeTank_in_progress', 
       'Observer_live', 'Observer_dead', 'Observer_in_progress', 
       'Sentry_live', 'Sentry_dead', 'Sentry_in_progress', 
       'Raven_live', 'Raven_dead', 'Raven_in_progress', 
       'Immortal_live', 'Immortal_dead', 'Immortal_in_progress', 
       'MissileTurret_live', 'MissileTurret_dead', 'MissileTurret_in_progress', 
       'StarportFlying_live', 'StarportFlying_dead', 'StarportFlying_in_progress', 
       'BarracksFlying_live', 'BarracksFlying_dead', 'BarracksFlying_in_progress', 
       'BarracksTechLab_live', 'BarracksTechLab_dead', 'BarracksTechLab_in_progress', 
       'StarportReactor_live', 'StarportReactor_dead', 'StarportReactor_in_progress', 
       'Charge', 
       'Archon_live', 'Archon_dead', 'Archon_in_progress', 
       'SiegeTankSieged_live', 'SiegeTankSieged_dead', 'SiegeTankSieged_in_progress', 
       'Zealot_live', 'Zealot_dead', 'Zealot_in_progress', 
       'WarpPrism_live', 'WarpPrism_dead', 'WarpPrism_in_progress', 
       'AutoTurret_live', 'AutoTurret_dead', 'AutoTurret_in_progress', 
       'TerranInfantryWeaponsLevel1', 
       'WarpPrismPhasing_live', 'WarpPrismPhasing_dead', 'WarpPrismPhasing_in_progress', 
       'FactoryFlying_live', 'FactoryFlying_dead', 'FactoryFlying_in_progress', 
       'Forge_live', 'Forge_dead', 'Forge_in_progress', 
       'Phoenix_live', 'Phoenix_dead', 'Phoenix_in_progress', 
       'FactoryReactor_live', 'FactoryReactor_dead', 'FactoryReactor_in_progress', 
       'Stimpack', 
       'Armory_live', 'Armory_dead', 'Armory_in_progress', 
       'WidowMine_live', 'WidowMine_dead', 'WidowMine_in_progress', 
       'Marauder_live', 'Marauder_dead', 'Marauder_in_progress', 
       'BlinkTech', 
       'GhostAcademy_live', 'GhostAcademy_dead', 'GhostAcademy_in_progress', 
       'TerranInfantryArmorsLevel1', 
       'WidowMineBurrowed_live', 'WidowMineBurrowed_dead', 'WidowMineBurrowed_in_progress', 
       'ProtossGroundWeaponsLevel1', 
       'RoboticsBay_live', 'RoboticsBay_dead', 'RoboticsBay_in_progress', 
       'Ghost_live', 'Ghost_dead', 'Ghost_in_progress', 
       'PunisherGrenades', 'ObserverSiegeMode_live', 'ObserverSiegeMode_dead', 
       'ObserverSiegeMode_in_progress', 
       'Colossus_live', 'Colossus_dead', 'Colossus_in_progress', 
       'SensorTower_live', 'SensorTower_dead', 'SensorTower_in_progress', 
       'ProtossGroundWeaponsLevel2', 
       'VikingFighter_live', 'VikingFighter_dead', 'VikingFighter_in_progress', 
       'EnhancedShockwaves', 
       'PhotonCannon_live', 'PhotonCannon_dead', 'PhotonCannon_in_progress', 
       'ExtendedThermalLance', 
       'Disruptor_live', 'Disruptor_dead', 'Disruptor_in_progress', 
       'TerranInfantryWeaponsLevel2', 
       'ProtossGroundArmorsLevel1', 
       'DarkTemplarBlinkUpgrade', 
       'CommandCenterFlying_live', 'CommandCenterFlying_dead', 'CommandCenterFlying_in_progress', 
       'GraviticDrive', 
       'PlanetaryFortress_live', 'PlanetaryFortress_dead', 'PlanetaryFortress_in_progress', 
       'TerranShipWeaponsLevel1', 
       'ProtossGroundWeaponsLevel3', 
       'Hellion_live', 'Hellion_dead', 'Hellion_in_progress', 
       'Bunker_live', 'Bunker_dead', 'Bunker_in_progress', 
       'Stargate_live', 'Stargate_dead', 'Stargate_in_progress', 
       'VoidRay_live', 'VoidRay_dead', 'VoidRay_in_progress', 
       'HighTemplar_live', 'HighTemplar_dead', 'HighTemplar_in_progress', 
       'PsiStormTech', 
       'Liberator_live', 'Liberator_dead', 'Liberator_in_progress', 
       'LiberatorAG_live', 'LiberatorAG_dead', 'LiberatorAG_in_progress', 
       'TerranInfantryArmorsLevel2', 
       'VikingAssault_live', 'VikingAssault_dead', 'VikingAssault_in_progress', 
       'ProtossGroundArmorsLevel2', 'TerranInfantryWeaponsLevel3', 'TerranInfantryArmorsLevel3', 
       'ProtossGroundArmorsLevel3', 'TerranShipWeaponsLevel2', 
       'FusionCore_live', 'FusionCore_dead', 'FusionCore_in_progress', 
       'PersonalCloaking', 
       'LiberatorAGRangeUpgrade', 
       'TerranShipWeaponsLevel3', 
       'Oracle_live', 'Oracle_dead', 'Oracle_in_progress', 
       'Banshee_live', 'Banshee_dead', 'Banshee_in_progress', 
       'BansheeCloak', 
       'TerranVehicleWeaponsLevel1', 
       'FleetBeacon_live', 'FleetBeacon_dead', 'FleetBeacon_in_progress', 
       'ObserverGraviticBooster', 
       'ProtossAirWeaponsLevel1', 
       'HiSecAutoTracking', 
       'TerranBuildingArmor', 
       'MedivacIncreaseSpeedBoost', 
       'ProtossShieldsLevel1', 
       'Carrier_live', 'Carrier_dead', 'Carrier_in_progress', 
       'Interceptor_live', 'Interceptor_dead', 'Interceptor_in_progress', 
       'Tempest_live', 'Tempest_dead', 'Tempest_in_progress', 
       'SmartServos', 
       'ProtossAirWeaponsLevel2', 
       'ProtossAirArmorsLevel1', 
       'ProtossAirArmorsLevel2', 
       'ProtossAirWeaponsLevel3', 
       'ProtossShieldsLevel2', 
       'Mothership_live', 'Mothership_dead', 'Mothership_in_progress', 
       'TerranVehicleAndShipArmorsLevel1', 
       'PhoenixRangeUpgrade', 
       'TerranVehicleAndShipArmorsLevel2', 
       'ProtossShieldsLevel3', 
       'DrillClaws', 
       'TerranVehicleAndShipArmorsLevel3', 
       'ProtossAirArmorsLevel3', 
       'TerranVehicleWeaponsLevel2', 
       'TerranVehicleWeaponsLevel3', 
       'Thor_live', 'Thor_dead', 'Thor_in_progress', 
       'ThorAP_live', 'ThorAP_dead', 'ThorAP_in_progress', 
       'AdeptPiercingAttack', 
       'Battlecruiser_live', 'Battlecruiser_dead', 'Battlecruiser_in_progress', 
       'BattlecruiserEnableSpecializations', 
       'CycloneLockOnDamageUpgrade', 'HellionTank_live', 'HellionTank_dead', 'HellionTank_in_progress']

zvt=['Terran_mineral_collection_rate', 'Terran_gas_collection_rate', 
     'Terran_unspent_minerals', 'Terran_unspent_gas', 
     'Zerg_mineral_collection_rate', 'Zerg_gas_collection_rate', 
     'Zerg_unspent_minerals', 'Zerg_unspent_gas', 
     'result', 
     'loop', 
     'SCV_live', 'SCV_dead', 'SCV_in_progress', 
     'CommandCenter_live', 'CommandCenter_dead', 'CommandCenter_in_progress', 
     'Egg_live', 'Egg_dead', 'Egg_in_progress', 
     'Larva_live', 'Larva_dead', 'Larva_in_progress', 
     'Drone_live', 'Drone_dead', 'Drone_in_progress', 
     'Overlord_live', 'Overlord_dead', 'Overlord_in_progress', 
     'Hatchery_live', 'Hatchery_dead', 'Hatchery_in_progress', 
     'SupplyDepot_live', 'SupplyDepot_dead', 'SupplyDepot_in_progress', 
     'Barracks_live', 'Barracks_dead', 'Barracks_in_progress', 
     'Refinery_live', 'Refinery_dead', 'Refinery_in_progress', 
     'SupplyDepotLowered_live', 'SupplyDepotLowered_dead', 'SupplyDepotLowered_in_progress', 
     'Extractor_live', 'Extractor_dead', 'Extractor_in_progress', 
     'SpawningPool_live', 'SpawningPool_dead', 'SpawningPool_in_progress', 
     'MULE_live', 'MULE_dead', 'MULE_in_progress', 
     'OrbitalCommand_live', 'OrbitalCommand_dead', 'OrbitalCommand_in_progress', 
     'Reaper_live', 'Reaper_dead', 'Reaper_in_progress', 
     'Factory_live', 'Factory_dead', 'Factory_in_progress', 
     'Marine_live', 'Marine_dead', 'Marine_in_progress', 
     'BarracksReactor_live', 'BarracksReactor_dead', 'BarracksReactor_in_progress', 
     'Zergling_live', 'Zergling_dead', 'Zergling_in_progress', 
     'Queen_live', 'Queen_dead', 'Queen_in_progress', 
     'CreepTumorQueen_live', 'CreepTumorQueen_dead', 'CreepTumorQueen_in_progress', 
     'CreepTumorBurrowed_live', 'CreepTumorBurrowed_dead', 'CreepTumorBurrowed_in_progress', 
     'FactoryFlying_live', 'FactoryFlying_dead', 'FactoryFlying_in_progress', 
     'BarracksFlying_live', 'BarracksFlying_dead', 'BarracksFlying_in_progress', 
     'FactoryReactor_live', 'FactoryReactor_dead', 'FactoryReactor_in_progress', 
     'BarracksTechLab_live', 'BarracksTechLab_dead', 'BarracksTechLab_in_progress', 
     'CreepTumor_live', 'CreepTumor_dead', 'CreepTumor_in_progress', 
     'Hellion_live', 'Hellion_dead', 'Hellion_in_progress', 
     'ZerglingMovementSpeed', 
     'Starport_live', 'Starport_dead', 'Starport_in_progress', 
     'StarportFlying_live', 'StarportFlying_dead', 'StarportFlying_in_progress', 
     'BanelingNest_live', 'BanelingNest_dead', 'BanelingNest_in_progress', 
     'StarportReactor_live', 'StarportReactor_dead', 'StarportReactor_in_progress', 
     'OrbitalCommandFlying_live', 'OrbitalCommandFlying_dead', 'OrbitalCommandFlying_in_progress', 
     'Armory_live', 'Armory_dead', 'Armory_in_progress', 
     'Stimpack', 
     'Medivac_live', 'Medivac_dead', 'Medivac_in_progress', 
     'EngineeringBay_live', 'EngineeringBay_dead', 'EngineeringBay_in_progress', 
     'Lair_live', 'Lair_dead', 'Lair_in_progress', 
     'EvolutionChamber_live', 'EvolutionChamber_dead', 'EvolutionChamber_in_progress', 
     'FactoryTechLab_live', 'FactoryTechLab_dead', 'FactoryTechLab_in_progress', 
     'WidowMine_live', 'WidowMine_dead', 'WidowMine_in_progress', 
     'OverlordCocoon_live', 'OverlordCocoon_dead', 'OverlordCocoon_in_progress', 
     'BanelingCocoon_live', 'BanelingCocoon_dead', 'BanelingCocoon_in_progress', 
     'Overseer_live', 'Overseer_dead', 'Overseer_in_progress', 
     'Baneling_live', 'Baneling_dead', 'Baneling_in_progress', 
     'InfestationPit_live', 'InfestationPit_dead', 'InfestationPit_in_progress', 
     'HellionTank_live', 'HellionTank_dead', 'HellionTank_in_progress', 
     'CentrificalHooks', 
     'SporeCrawler_live', 'SporeCrawler_dead', 'SporeCrawler_in_progress', 
     'OverlordSpeed', 
     'WidowMineBurrowed_live', 'WidowMineBurrowed_dead', 'WidowMineBurrowed_in_progress', 
     'DrillClaws', 
     'TerranInfantryArmorsLevel1', 
     'TerranInfantryWeaponsLevel1', 
     'ZergMeleeWeaponsLevel1', 
     'ZergGroundArmorsLevel1', 
     'Liberator_live', 'Liberator_dead', 'Liberator_in_progress', 
     'LiberatorAG_live', 'LiberatorAG_dead', 'LiberatorAG_in_progress', 
     'HydraliskDen_live', 'HydraliskDen_dead', 'HydraliskDen_in_progress', 
     'Hydralisk_live', 'Hydralisk_dead', 'Hydralisk_in_progress', 
     'Marauder_live', 'Marauder_dead', 'Marauder_in_progress', 
     'EvolveMuscularAugments', 
     'CommandCenterFlying_live', 'CommandCenterFlying_dead', 'CommandCenterFlying_in_progress', 
     'TerranInfantryWeaponsLevel2', 
     'TerranInfantryArmorsLevel2', 
     'EvolveGroovedSpines', 
     'SensorTower_live', 'SensorTower_dead', 'SensorTower_in_progress', 
     'PunisherGrenades', 
     'ZergGroundArmorsLevel2', 
     'Hive_live', 'Hive_dead', 'Hive_in_progress', 
     'TerranVehicleAndShipArmorsLevel1', 
     'ZergMeleeWeaponsLevel2', 
     'Viper_live', 'Viper_dead', 'Viper_in_progress', 
     'StarportTechLab_live', 'StarportTechLab_dead', 'StarportTechLab_in_progress', 
     'Banshee_live', 'Banshee_dead', 'Banshee_in_progress', 
     'BansheeCloak', 
     'SiegeTank_live', 'SiegeTank_dead', 'SiegeTank_in_progress', 
     'SiegeTankSieged_live', 'SiegeTankSieged_dead', 'SiegeTankSieged_in_progress', 
     'Broodling_live', 'Broodling_dead', 'Broodling_in_progress', 
     'VikingFighter_live', 'VikingFighter_dead', 'VikingFighter_in_progress', 
     'ThorAP_live', 'ThorAP_dead', 'ThorAP_in_progress', 
     'RoachWarren_live', 'RoachWarren_dead', 'RoachWarren_in_progress', 
     'VikingAssault_live', 'VikingAssault_dead', 'VikingAssault_in_progress', 
     'Thor_live', 'Thor_dead', 'Thor_in_progress', 
     'Roach_live', 'Roach_dead', 'Roach_in_progress', 
     'MissileTurret_live', 'MissileTurret_dead', 'MissileTurret_in_progress', 
     'CycloneLockOnDamageUpgrade', 
     'SpineCrawler_live', 'SpineCrawler_dead', 'SpineCrawler_in_progress', 
     'RavagerCocoon_live', 'RavagerCocoon_dead', 'RavagerCocoon_in_progress', 
     'Ravager_live', 'Ravager_dead', 'Ravager_in_progress', 
     'HighCapacityBarrels', 
     'SwarmHostMP_live', 'SwarmHostMP_dead', 'SwarmHostMP_in_progress', 
     'GlialReconstitution', 
     'ZergMissileWeaponsLevel1', 
     'TerranVehicleAndShipArmorsLevel2', 
     'SmartServos', 
     'LocustMPFlying_live', 'LocustMPFlying_dead', 'LocustMPFlying_in_progress', 
     'Cyclone_live', 'Cyclone_dead', 'Cyclone_in_progress', 
     'LocustMPPrecursor_live', 'LocustMPPrecursor_dead', 'LocustMPPrecursor_in_progress', 
     'LocustMP_live', 'LocustMP_dead', 'LocustMP_in_progress', 
     'BansheeSpeed', 
     'PlanetaryFortress_live', 'PlanetaryFortress_dead', 'PlanetaryFortress_in_progress', 
     'ZergMissileWeaponsLevel2', 
     'TerranVehicleWeaponsLevel1', 
     'ZerglingAttackSpeed', 
     'Spire_live', 'Spire_dead', 'Spire_in_progress', 
     'ZergMeleeWeaponsLevel3', 
     'ZergMissileWeaponsLevel3', 
     'TerranVehicleWeaponsLevel2', 
     'Burrow', 
     'Bunker_live', 'Bunker_dead', 'Bunker_in_progress', 
     'Mutalisk_live', 'Mutalisk_dead', 'Mutalisk_in_progress', 
     'UltraliskCavern_live', 'UltraliskCavern_dead', 'UltraliskCavern_in_progress', 
     'Ultralisk_live', 'Ultralisk_dead', 'Ultralisk_in_progress', 
     'ChitinousPlating', 
     'AnabolicSynthesis', 
     'ZergGroundArmorsLevel3', 
     'OverseerSiegeMode_live', 'OverseerSiegeMode_dead', 'OverseerSiegeMode_in_progress', 
     'Infestor_live', 'Infestor_dead', 'Infestor_in_progress', 
     'GhostAcademy_live', 'GhostAcademy_dead', 'GhostAcademy_in_progress', 
     'LurkerDenMP_live', 'LurkerDenMP_dead', 'LurkerDenMP_in_progress', 
     'LurkerMPEgg_live', 'LurkerMPEgg_dead', 'LurkerMPEgg_in_progress', 
     'TerranInfantryWeaponsLevel3', 
     'LurkerMP_live', 'LurkerMP_dead', 'LurkerMP_in_progress', 
     'LurkerMPBurrowed_live', 'LurkerMPBurrowed_dead', 'LurkerMPBurrowed_in_progress', 
     'LurkerRange', 
     'Ghost_live', 'Ghost_dead', 'Ghost_in_progress', 
     'PersonalCloaking', 
     'DiggingClaws', 
     'TerranInfantryArmorsLevel3', 
     'FusionCore_live', 'FusionCore_dead', 'FusionCore_in_progress', 
     'HiSecAutoTracking', 
     'EnhancedShockwaves', 
     'TerranBuildingArmor', 
     'NydusNetwork_live', 'NydusNetwork_dead', 'NydusNetwork_in_progress', 
     'InfestorEnergyUpgrade', 
     'NydusCanal_live', 'NydusCanal_dead', 'NydusCanal_in_progress', 
     'TransportOverlordCocoon_live', 'TransportOverlordCocoon_dead', 'TransportOverlordCocoon_in_progress', 
     'OverlordTransport_live', 'OverlordTransport_dead', 'OverlordTransport_in_progress', 
     'NeuralParasite', 'GreaterSpire_live', 'GreaterSpire_dead', 'GreaterSpire_in_progress', 
     'ZergFlyerWeaponsLevel1', 
     'ZergFlyerArmorsLevel1', 
     'LiberatorAGRangeUpgrade', 
     'Corruptor_live', 'Corruptor_dead', 'Corruptor_in_progress', 
     'ZergFlyerWeaponsLevel2', 
     'BroodLordCocoon_live', 'BroodLordCocoon_dead', 'BroodLordCocoon_in_progress', 
     'BroodLord_live', 'BroodLord_dead', 'BroodLord_in_progress', 
     'BroodlingEscort_live', 'BroodlingEscort_dead', 'BroodlingEscort_in_progress', 
     'TerranVehicleWeaponsLevel3', 
     'TerranVehicleAndShipArmorsLevel3', 
     'ZergFlyerWeaponsLevel3', 
     'ZergFlyerArmorsLevel2', 
     'TerranShipWeaponsLevel1', 
     'ZergFlyerArmorsLevel3', 
     'TerranShipWeaponsLevel2', 
     'Battlecruiser_live', 'Battlecruiser_dead', 'Battlecruiser_in_progress', 
     'BattlecruiserEnableSpecializations', 
     'Raven_live', 'Raven_dead', 'Raven_in_progress', 
     'AutoTurret_live', 'AutoTurret_dead', 'AutoTurret_in_progress', 
     'MedivacIncreaseSpeedBoost', 
     'TunnelingClaws', 
     'TerranShipWeaponsLevel3']

pvz = ['Protoss_mineral_collection_rate', 'Protoss_gas_collection_rate', 
       'Protoss_unspent_minerals', 'Protoss_unspent_gas', 
       'Zerg_mineral_collection_rate', 'Zerg_gas_collection_rate', 
       'Zerg_unspent_minerals', 'Zerg_unspent_gas', 
       'result', 
       'loop', 
       'Probe_live', 'Probe_dead', 'Probe_in_progress', 
       'Nexus_live', 'Nexus_dead', 'Nexus_in_progress', 
       'Egg_live', 'Egg_dead', 'Egg_in_progress', 
       'Larva_live', 'Larva_dead', 'Larva_in_progress', 
       'Drone_live', 'Drone_dead', 'Drone_in_progress', 
       'Overlord_live', 'Overlord_dead', 'Overlord_in_progress', 
       'Hatchery_live', 'Hatchery_dead', 'Hatchery_in_progress', 
       'Pylon_live', 'Pylon_dead', 'Pylon_in_progress', 
       'Gateway_live', 'Gateway_dead', 'Gateway_in_progress', 
       'Assimilator_live', 'Assimilator_dead', 'Assimilator_in_progress', 
       'Extractor_live', 'Extractor_dead', 'Extractor_in_progress', 
       'SpawningPool_live', 'SpawningPool_dead', 'SpawningPool_in_progress', 
       'CyberneticsCore_live', 'CyberneticsCore_dead', 'CyberneticsCore_in_progress', 
       'Stargate_live', 'Stargate_dead', 'Stargate_in_progress', 
       'Zergling_live', 'Zergling_dead', 'Zergling_in_progress', 
       'Adept_live', 'Adept_dead', 'Adept_in_progress', 
       'Queen_live', 'Queen_dead', 'Queen_in_progress', 
       'CreepTumorQueen_live', 'CreepTumorQueen_dead', 'CreepTumorQueen_in_progress', 
       'SporeCrawler_live', 'SporeCrawler_dead', 'SporeCrawler_in_progress', 
       'ZerglingMovementSpeed', 
       'CreepTumorBurrowed_live', 'CreepTumorBurrowed_dead', 'CreepTumorBurrowed_in_progress', 
       'VoidRay_live', 'VoidRay_dead', 'VoidRay_in_progress', 
       'CreepTumor_live', 'CreepTumor_dead', 'CreepTumor_in_progress', 
       'Oracle_live', 'Oracle_dead', 'Oracle_in_progress', 
       'WarpGateResearch', 
       'WarpGate_live', 'WarpGate_dead', 'WarpGate_in_progress', 
       'EvolutionChamber_live', 'EvolutionChamber_dead', 'EvolutionChamber_in_progress', 
       'ShieldBattery_live', 'ShieldBattery_dead', 'ShieldBattery_in_progress', 
       'Stalker_live', 'Stalker_dead', 'Stalker_in_progress', 
       'Phoenix_live', 'Phoenix_dead', 'Phoenix_in_progress', 
       'BanelingNest_live', 'BanelingNest_dead', 'BanelingNest_in_progress', 
       'Lair_live', 'Lair_dead', 'Lair_in_progress', 
       'Forge_live', 'Forge_dead', 'Forge_in_progress', 
       'Zealot_live', 'Zealot_dead', 'Zealot_in_progress', 
       'TwilightCouncil_live', 'TwilightCouncil_dead', 'TwilightCouncil_in_progress', 
       'InfestationPit_live', 'InfestationPit_dead', 'InfestationPit_in_progress', 
       'ZergMeleeWeaponsLevel1', 
       'PhotonCannon_live', 'PhotonCannon_dead', 'PhotonCannon_in_progress', 
       'Sentry_live', 'Sentry_dead', 'Sentry_in_progress', 
       'CentrificalHooks', 
       'HighTemplar_live', 'HighTemplar_dead', 'HighTemplar_in_progress', 
       'Archon_live', 'Archon_dead', 'Archon_in_progress', 
       'Hive_live', 'Hive_dead', 'Hive_in_progress', 
       'Charge', 
       'Viper_live', 'Viper_dead', 'Viper_in_progress', 
       'UltraliskCavern_live', 'UltraliskCavern_dead', 'UltraliskCavern_in_progress', 
       'ZergGroundArmorsLevel1', 
       'BanelingCocoon_live', 'BanelingCocoon_dead', 'BanelingCocoon_in_progress', 
       'ZergMeleeWeaponsLevel2', 
       'Baneling_live', 'Baneling_dead', 'Baneling_in_progress', 
       'ZerglingAttackSpeed', 
       'PsiStormTech', 
       'ProtossGroundWeaponsLevel1', 
       'Ultralisk_live', 'Ultralisk_dead', 'Ultralisk_in_progress', 
       'ChitinousPlating', 
       'SpineCrawler_live', 'SpineCrawler_dead', 'SpineCrawler_in_progress', 
       'ProtossAirWeaponsLevel1', 
       'ZergGroundArmorsLevel2', 
       'BlinkTech', 
       'AnabolicSynthesis', 
       'RoboticsFacility_live', 'RoboticsFacility_dead', 'RoboticsFacility_in_progress', 
       'ZergMeleeWeaponsLevel3', 
       'Burrow', 
       'Spire_live', 'Spire_dead', 'Spire_in_progress', 
       'ProtossGroundWeaponsLevel2', 
       'Immortal_live', 'Immortal_dead', 'Immortal_in_progress', 
       'Observer_live', 'Observer_dead', 'Observer_in_progress', 
       'RoachWarren_live', 'RoachWarren_dead', 'RoachWarren_in_progress', 
       'OverlordCocoon_live', 'OverlordCocoon_dead', 'OverlordCocoon_in_progress', 
       'RoboticsBay_live', 'RoboticsBay_dead', 'RoboticsBay_in_progress', 
       'Overseer_live', 'Overseer_dead', 'Overseer_in_progress', 
       'Roach_live', 'Roach_dead', 'Roach_in_progress', 
       'OverlordSpeed', 
       'WarpPrism_live', 'WarpPrism_dead', 'WarpPrism_in_progress', 
       'GlialReconstitution', 
       'Disruptor_live', 'Disruptor_dead', 'Disruptor_in_progress', 
       'Mutalisk_live', 'Mutalisk_dead', 'Mutalisk_in_progress', 
       'WarpPrismPhasing_live', 'WarpPrismPhasing_dead', 'WarpPrismPhasing_in_progress', 
       'ZergFlyerWeaponsLevel1', 
       'DarkShrine_live', 'DarkShrine_dead', 'DarkShrine_in_progress', 
       'FleetBeacon_live', 'FleetBeacon_dead', 'FleetBeacon_in_progress', 
       'Corruptor_live', 'Corruptor_dead', 'Corruptor_in_progress', 
       'DarkTemplar_live', 'DarkTemplar_dead', 'DarkTemplar_in_progress', 
       'ZergFlyerWeaponsLevel2', 
       'PhoenixRangeUpgrade', 
       'ProtossGroundWeaponsLevel3', 
       'Broodling_live', 'Broodling_dead', 'Broodling_in_progress', 
       'ProtossShieldsLevel1', 
       'RavagerCocoon_live', 'RavagerCocoon_dead', 'RavagerCocoon_in_progress', 
       'Ravager_live', 'Ravager_dead', 'Ravager_in_progress', 
       'ObserverSiegeMode_live', 'ObserverSiegeMode_dead', 'ObserverSiegeMode_in_progress', 
       'TransportOverlordCocoon_live', 'TransportOverlordCocoon_dead', 'TransportOverlordCocoon_in_progress', 
       'OverlordTransport_live', 'OverlordTransport_dead', 'OverlordTransport_in_progress', 
       'ZergMissileWeaponsLevel1', 
       'AdeptPiercingAttack', 
       'OverseerSiegeMode_live', 'OverseerSiegeMode_dead', 'OverseerSiegeMode_in_progress', 
       'ZergMissileWeaponsLevel2', 
       'GreaterSpire_live', 'GreaterSpire_dead', 'GreaterSpire_in_progress', 
       'BroodLordCocoon_live', 'BroodLordCocoon_dead', 'BroodLordCocoon_in_progress', 
       'BroodLord_live', 'BroodLord_dead', 'BroodLord_in_progress', 
       'BroodlingEscort_live', 'BroodlingEscort_dead', 'BroodlingEscort_in_progress', 
       'ProtossGroundArmorsLevel1', 
       'InfestorEnergyUpgrade', 
       'Infestor_live', 'Infestor_dead', 'Infestor_in_progress', 
       'NeuralParasite', 
       'ProtossGroundArmorsLevel2', 
       'ProtossShieldsLevel2', 
       'ProtossGroundArmorsLevel3', 
       'ObserverGraviticBooster', 
       'NydusNetwork_live', 'NydusNetwork_dead', 'NydusNetwork_in_progress', 
       'NydusCanal_live', 'NydusCanal_dead', 'NydusCanal_in_progress', 
       'HydraliskDen_live', 'HydraliskDen_dead', 'HydraliskDen_in_progress', 
       'LurkerDenMP_live', 'LurkerDenMP_dead', 'LurkerDenMP_in_progress', 
       'Hydralisk_live', 'Hydralisk_dead', 'Hydralisk_in_progress', 
       'EvolveGroovedSpines', 
       'LurkerMPEgg_live', 'LurkerMPEgg_dead', 'LurkerMPEgg_in_progress', 
       'LurkerMP_live', 'LurkerMP_dead', 'LurkerMP_in_progress', 
       'LurkerMPBurrowed_live', 'LurkerMPBurrowed_dead', 'LurkerMPBurrowed_in_progress', 
       'LurkerRange', 
       'EvolveMuscularAugments', 
       'DiggingClaws', 
       'ProtossShieldsLevel3', 
       'Carrier_live', 'Carrier_dead', 'Carrier_in_progress', 
       'Interceptor_live', 'Interceptor_dead', 'Interceptor_in_progress', 
       'Colossus_live', 'Colossus_dead', 'Colossus_in_progress', 
       'DarkTemplarBlinkUpgrade', 
       'ZergMissileWeaponsLevel3', 
       'Tempest_live', 'Tempest_dead', 'Tempest_in_progress', 
       'GraviticDrive', 
       'ZergFlyerArmorsLevel1', 
       'ProtossAirWeaponsLevel2', 
       'ProtossAirWeaponsLevel3', 
       'Mothership_live', 'Mothership_dead', 'Mothership_in_progress', 
       'ZergFlyerArmorsLevel2', 
       'ProtossAirArmorsLevel1', 
       'ZergGroundArmorsLevel3', 
       'ZergFlyerWeaponsLevel3', 
       'ZergFlyerArmorsLevel3', 
       'SwarmHostMP_live', 'SwarmHostMP_dead', 'SwarmHostMP_in_progress', 
       'LocustMPFlying_live', 'LocustMPFlying_dead', 'LocustMPFlying_in_progress', 
       'LocustMP_live', 'LocustMP_dead', 'LocustMP_in_progress', 
       'LocustMPPrecursor_live', 'LocustMPPrecursor_dead', 'LocustMPPrecursor_in_progress', 
       'ExtendedThermalLance', 
       'ProtossAirArmorsLevel2', 'ProtossAirArmorsLevel3', 
       'TunnelingClaws', 
       'BarracksReactor_live', 'BarracksReactor_dead', 'BarracksReactor_in_progress', 
       'FactoryFlying_live', 'FactoryFlying_dead', 'FactoryFlying_in_progress', 
       'FactoryReactor_live', 'FactoryReactor_dead', 'FactoryReactor_in_progress',
         'BarracksTechLab_live', 'BarracksTechLab_dead', 'BarracksTechLab_in_progress', 
         'Hellion_live', 'Hellion_dead', 'Hellion_in_progress', 'StarportFlying_live', 
         'StarportFlying_dead', 'StarportFlying_in_progress', 'OrbitalCommandFlying_live', 
         'OrbitalCommandFlying_dead', 'OrbitalCommandFlying_in_progress', 'EngineeringBay_live', 
         'EngineeringBay_dead', 'EngineeringBay_in_progress', 'BansheeCloak', 'StarportReactor_live',
         'StarportReactor_dead', 'StarportReactor_in_progress', 'Stimpack', 'SiegeTank_live', 'SiegeTank_dead', 
         'SiegeTank_in_progress', 'Armory_live', 'Armory_dead', 'Armory_in_progress', 'Medivac_live', 'Medivac_dead', 
         'Medivac_in_progress', 'MissileTurret_live', 'MissileTurret_dead', 'MissileTurret_in_progress']

tvt=['player_1_Terran_mineral_collection_rate', 'player_1_Terran_gas_collection_rate', 
     'player_1_Terran_unspent_minerals', 'player_1_Terran_unspent_gas', 
     'player_2_Terran_mineral_collection_rate', 'player_2_Terran_gas_collection_rate', 
     'player_2_Terran_unspent_minerals', 'player_2_Terran_unspent_gas', 
     'result', 
     'loop', 
     'player_1_SCV_live', 'player_1_SCV_dead', 'player_1_SCV_in_progress', 
     'player_1_CommandCenter_live', 'player_1_CommandCenter_dead', 'player_1_CommandCenter_in_progress', 
     'player_2_SCV_live', 'player_2_SCV_dead', 'player_2_SCV_in_progress', 
     'player_2_CommandCenter_live', 'player_2_CommandCenter_dead', 'player_2_CommandCenter_in_progress', 
     'player_1_SupplyDepot_live', 'player_1_SupplyDepot_dead', 'player_1_SupplyDepot_in_progress', 
     'player_2_SupplyDepot_live', 'player_2_SupplyDepot_dead', 'player_2_SupplyDepot_in_progress', 
     'player_2_Refinery_live', 'player_2_Refinery_dead', 'player_2_Refinery_in_progress', 
     'player_1_SupplyDepotLowered_live', 'player_1_SupplyDepotLowered_dead', 'player_1_SupplyDepotLowered_in_progress', 
     'player_1_Barracks_live', 'player_1_Barracks_dead', 'player_1_Barracks_in_progress', 
     'player_2_SupplyDepotLowered_live', 'player_2_SupplyDepotLowered_dead', 'player_2_SupplyDepotLowered_in_progress', 
     'player_1_Refinery_live', 'player_1_Refinery_dead', 'player_1_Refinery_in_progress', 
     'player_2_Barracks_live', 'player_2_Barracks_dead', 'player_2_Barracks_in_progress', 
     'player_1_Factory_live', 'player_1_Factory_dead', 'player_1_Factory_in_progress', 
     'player_1_OrbitalCommand_live', 'player_1_OrbitalCommand_dead', 'player_1_OrbitalCommand_in_progress', 
     'player_2_Factory_live', 'player_2_Factory_dead', 'player_2_Factory_in_progress', 
     'player_1_MULE_live', 'player_1_MULE_dead', 'player_1_MULE_in_progress', 
     'player_2_MULE_live', 'player_2_MULE_dead', 'player_2_MULE_in_progress', 
     'player_2_OrbitalCommand_live', 'player_2_OrbitalCommand_dead', 'player_2_OrbitalCommand_in_progress', 
     'player_1_Reaper_live', 'player_1_Reaper_dead', 'player_1_Reaper_in_progress', 
     'player_2_Reaper_live', 'player_2_Reaper_dead', 'player_2_Reaper_in_progress', 
     'player_1_BarracksReactor_live', 'player_1_BarracksReactor_dead', 'player_1_BarracksReactor_in_progress', 
     'player_2_Starport_live', 'player_2_Starport_dead', 'player_2_Starport_in_progress', 
     'player_1_Starport_live', 'player_1_Starport_dead', 'player_1_Starport_in_progress', 
     'player_1_Hellion_live', 'player_1_Hellion_dead', 'player_1_Hellion_in_progress', 
     'player_1_FactoryTechLab_live', 'player_1_FactoryTechLab_dead', 'player_1_FactoryTechLab_in_progress', 
     'player_2_Hellion_live', 'player_2_Hellion_dead', 'player_2_Hellion_in_progress', 
     'player_2_Marine_live', 'player_2_Marine_dead', 'player_2_Marine_in_progress', 
     'player_2_BarracksTechLab_live', 'player_2_BarracksTechLab_dead', 'player_2_BarracksTechLab_in_progress', 
     'player_2_StarportFlying_live', 'player_2_StarportFlying_dead', 'player_2_StarportFlying_in_progress', 
     'player_2_BarracksFlying_live', 'player_2_BarracksFlying_dead', 'player_2_BarracksFlying_in_progress', 
     'player_2_StarportTechLab_live', 'player_2_StarportTechLab_dead', 'player_2_StarportTechLab_in_progress', 
     'player_1_Marine_live', 'player_1_Marine_dead', 'player_1_Marine_in_progress', 
     'player_2_BarracksReactor_live', 'player_2_BarracksReactor_dead', 'player_2_BarracksReactor_in_progress', 
     'player_2_FactoryTechLab_live', 'player_2_FactoryTechLab_dead', 'player_2_FactoryTechLab_in_progress', 
     'player_1_Cyclone_live', 'player_1_Cyclone_dead', 'player_1_Cyclone_in_progress', 
     'player_1_FactoryFlying_live', 'player_1_FactoryFlying_dead', 'player_1_FactoryFlying_in_progress', 
     'player_1_Medivac_live', 'player_1_Medivac_dead', 'player_1_Medivac_in_progress', 
     'player_1_StarportFlying_live', 'player_1_StarportFlying_dead', 'player_1_StarportFlying_in_progress', 
     'player_1_StarportTechLab_live', 'player_1_StarportTechLab_dead', 'player_1_StarportTechLab_in_progress', 
     'player_2_Raven_live', 'player_2_Raven_dead', 'player_2_Raven_in_progress', 
     'player_2_Cyclone_live', 'player_2_Cyclone_dead', 'player_2_Cyclone_in_progress', 
     'player_1_Raven_live', 'player_1_Raven_dead', 'player_1_Raven_in_progress', 
     'player_1_SiegeTank_live', 'player_1_SiegeTank_dead', 'player_1_SiegeTank_in_progress', 
     'player_1_AutoTurret_live', 'player_1_AutoTurret_dead', 'player_1_AutoTurret_in_progress', 
     'player_2_SiegeTank_live', 'player_2_SiegeTank_dead', 'player_2_SiegeTank_in_progress', 
     'player_1_BarracksFlying_live', 'player_1_BarracksFlying_dead', 'player_1_BarracksFlying_in_progress', 
     'player_2_SiegeTankSieged_live', 'player_2_SiegeTankSieged_dead', 'player_2_SiegeTankSieged_in_progress', 
     'player_1_StarportReactor_live', 'player_1_StarportReactor_dead', 'player_1_StarportReactor_in_progress', 
     'player_1_BarracksTechLab_live', 'player_1_BarracksTechLab_dead', 'player_1_BarracksTechLab_in_progress', 
     'player_2_OrbitalCommandFlying_live', 'player_2_OrbitalCommandFlying_dead', 'player_2_OrbitalCommandFlying_in_progress', 
     'player_2_EngineeringBay_live', 'player_2_EngineeringBay_dead', 'player_2_EngineeringBay_in_progress', 
     'player_1_VikingFighter_live', 'player_1_VikingFighter_dead', 'player_1_VikingFighter_in_progress', 
     'player_2_StarportReactor_live', 'player_2_StarportReactor_dead', 'player_2_StarportReactor_in_progress', 
     'player_1_OrbitalCommandFlying_live', 'player_1_OrbitalCommandFlying_dead', 'player_1_OrbitalCommandFlying_in_progress', 
     'player_1_EngineeringBay_live', 'player_1_EngineeringBay_dead', 'player_1_EngineeringBay_in_progress',
       'player_1_SiegeTankSieged_live', 'player_1_SiegeTankSieged_dead', 'player_1_SiegeTankSieged_in_progress', 
       'player_2_VikingFighter_live', 'player_2_VikingFighter_dead', 'player_2_VikingFighter_in_progress', 
       'player_2_AutoTurret_live', 'player_2_AutoTurret_dead', 'player_2_AutoTurret_in_progress', 
       'player_1_VikingAssault_live', 'player_1_VikingAssault_dead', 'player_1_VikingAssault_in_progress', 
       'player_1_Stimpack', 
       'player_2_TerranInfantryWeaponsLevel1', 
       'player_1_Liberator_live', 'player_1_Liberator_dead', 'player_1_Liberator_in_progress', 
       'player_2_Armory_live', 'player_2_Armory_dead', 'player_2_Armory_in_progress', 
       'player_2_TerranInfantryArmorsLevel1', 
       'player_1_Armory_live', 'player_1_Armory_dead', 'player_1_Armory_in_progress', 
       'player_1_TerranInfantryWeaponsLevel1', 
       'player_1_SensorTower_live', 'player_1_SensorTower_dead', 'player_1_SensorTower_in_progress', 
       'player_1_TerranInfantryArmorsLevel1', 
       'player_2_Stimpack', 
       'player_2_SensorTower_live', 'player_2_SensorTower_dead', 'player_2_SensorTower_in_progress', 
       'player_1_CommandCenterFlying_live', 'player_1_CommandCenterFlying_dead', 'player_1_CommandCenterFlying_in_progress', 
       'player_2_MissileTurret_live', 'player_2_MissileTurret_dead', 'player_2_MissileTurret_in_progress', 
       'player_2_Medivac_live', 'player_2_Medivac_dead', 'player_2_Medivac_in_progress', 
       'player_1_LiberatorAG_live', 'player_1_LiberatorAG_dead', 'player_1_LiberatorAG_in_progress', 
       'player_1_PlanetaryFortress_live', 
       'player_1_PlanetaryFortress_dead', 'player_1_PlanetaryFortress_in_progress', 
       'player_2_CommandCenterFlying_live', 'player_2_CommandCenterFlying_dead', 'player_2_CommandCenterFlying_in_progress', 
       'player_1_TerranInfantryWeaponsLevel2', 
       'player_2_TerranVehicleWeaponsLevel1', 
       'player_2_TerranInfantryWeaponsLevel2', 
       'player_2_TerranInfantryArmorsLevel2', 
       'player_1_TerranInfantryArmorsLevel2', 
       'player_2_PlanetaryFortress_live', 'player_2_PlanetaryFortress_dead', 'player_2_PlanetaryFortress_in_progress', 
       'player_1_TerranVehicleWeaponsLevel1', 
       'player_1_HellionTank_live', 'player_1_HellionTank_dead', 'player_1_HellionTank_in_progress', 
       'player_1_MissileTurret_live', 'player_1_MissileTurret_dead', 'player_1_MissileTurret_in_progress', 
       'player_1_TerranInfantryWeaponsLevel3', 
       'player_1_TerranInfantryArmorsLevel3', 
       'player_2_TerranInfantryWeaponsLevel3', 
       'player_1_TerranVehicleWeaponsLevel2', 
       'player_2_TerranInfantryArmorsLevel3', 
       'player_1_TerranBuildingArmor', 
       'player_1_TerranVehicleAndShipArmorsLevel1', 
       'player_1_RavenCorvidReactor', 
       'player_2_VikingAssault_live', 'player_2_VikingAssault_dead', 'player_2_VikingAssault_in_progress', 
       'player_1_FactoryReactor_live', 'player_1_FactoryReactor_dead', 'player_1_FactoryReactor_in_progress', 
       'player_2_FusionCore_live', 'player_2_FusionCore_dead', 'player_2_FusionCore_in_progress', 
       'player_2_Battlecruiser_live', 'player_2_Battlecruiser_dead', 'player_2_Battlecruiser_in_progress', 
       'player_2_BattlecruiserEnableSpecializations', 
       'player_2_CycloneLockOnDamageUpgrade', 
       'player_1_SmartServos', 
       'player_1_HighCapacityBarrels', 
       'player_1_CycloneLockOnDamageUpgrade', 
       'player_2_HighCapacityBarrels',
         'player_1_TerranShipWeaponsLevel1', 
         'player_2_Bunker_live', 'player_2_Bunker_dead', 'player_2_Bunker_in_progress', 
         'player_2_Marauder_live', 'player_2_Marauder_dead', 'player_2_Marauder_in_progress', 
         'player_2_PunisherGrenades', 
         'player_2_FactoryFlying_live', 'player_2_FactoryFlying_dead', 'player_2_FactoryFlying_in_progress', 
         'player_1_WidowMine_live', 'player_1_WidowMine_dead', 'player_1_WidowMine_in_progress', 
         'player_1_WidowMineBurrowed_live', 'player_1_WidowMineBurrowed_dead', 'player_1_WidowMineBurrowed_in_progress', 
         'player_1_Banshee_live', 'player_1_Banshee_dead', 'player_1_Banshee_in_progress', 
         'player_1_FusionCore_live', 'player_1_FusionCore_dead', 'player_1_FusionCore_in_progress', 
         'player_1_HiSecAutoTracking', 
         'player_1_Bunker_live', 'player_1_Bunker_dead', 'player_1_Bunker_in_progress', 
         'player_1_Marauder_live', 'player_1_Marauder_dead', 'player_1_Marauder_in_progress', 
         'player_1_PunisherGrenades', 
         'player_2_WidowMine_live', 'player_2_WidowMine_dead', 'player_2_WidowMine_in_progress', 
         'player_2_WidowMineBurrowed_live', 'player_2_WidowMineBurrowed_dead', 'player_2_WidowMineBurrowed_in_progress', 
         'player_2_TerranShipWeaponsLevel1', 'player_2_TerranVehicleAndShipArmorsLevel1',
           'player_2_FactoryReactor_live', 'player_2_FactoryReactor_dead', 'player_2_FactoryReactor_in_progress', 
           'player_2_Banshee_live', 'player_2_Banshee_dead', 'player_2_Banshee_in_progress', 
           'player_2_RavenCorvidReactor', 
           'player_2_Liberator_live', 'player_2_Liberator_dead', 'player_2_Liberator_in_progress', 
           'player_2_LiberatorAG_live', 'player_2_LiberatorAG_dead', 'player_2_LiberatorAG_in_progress', 
           'player_2_TerranVehicleWeaponsLevel2', 
           'player_2_HellionTank_live', 'player_2_HellionTank_dead', 'player_2_HellionTank_in_progress', 
           'player_2_BansheeCloak', 
           'player_2_BansheeSpeed', 
           'player_2_Thor_live', 'player_2_Thor_dead', 'player_2_Thor_in_progress', 
           'player_2_ThorAP_live', 'player_2_ThorAP_dead', 'player_2_ThorAP_in_progress', 
           'player_2_TerranVehicleAndShipArmorsLevel2', 
           'player_2_SmartServos', 
           'player_1_LiberatorAGRangeUpgrade', 
           'player_2_TerranVehicleWeaponsLevel3', 
           'player_2_TerranVehicleAndShipArmorsLevel3', 
           'player_2_DrillClaws', 
           'player_1_Battlecruiser_live', 'player_1_Battlecruiser_dead', 'player_1_Battlecruiser_in_progress', 
           'player_1_BattlecruiserEnableSpecializations', 
           'player_2_LiberatorAGRangeUpgrade', 
           'player_1_TerranVehicleAndShipArmorsLevel2', 
           'player_1_TerranVehicleAndShipArmorsLevel3', 
           'player_1_TerranVehicleWeaponsLevel3', 
           'player_1_Thor_live', 'player_1_Thor_dead', 'player_1_Thor_in_progress', 
           'player_2_HiSecAutoTracking', 
           'player_2_TerranBuildingArmor', 
           'player_2_TerranShipWeaponsLevel2', 
           'player_1_TerranShipWeaponsLevel2', 
           'player_2_TerranShipWeaponsLevel3', 
           'player_1_TerranShipWeaponsLevel3', 
           'player_1_ThorAP_live', 'player_1_ThorAP_dead', 'player_1_ThorAP_in_progress', 
           'player_1_DrillClaws', 
           'player_1_BansheeCloak', 
           'player_2_MedivacIncreaseSpeedBoost', 
           'player_2_GhostAcademy_live', 'player_2_GhostAcademy_dead', 'player_2_GhostAcademy_in_progress', 
           'player_2_Ghost_live', 'player_2_Ghost_dead', 'player_2_Ghost_in_progress', 
           'player_2_PersonalCloaking', 
           'player_1_BansheeSpeed']

zvz=['player_1_Zerg_mineral_collection_rate', 'player_1_Zerg_gas_collection_rate', 
     'player_1_Zerg_unspent_minerals', 'player_1_Zerg_unspent_gas', 
     'player_2_Zerg_mineral_collection_rate', 'player_2_Zerg_gas_collection_rate',
     'player_2_Zerg_unspent_minerals', 'player_2_Zerg_unspent_gas', 
     'result', 
     'loop', 
     'player_1_Egg_live', 'player_1_Egg_dead', 'player_1_Egg_in_progress', 
     'player_1_Larva_live', 'player_1_Larva_dead', 'player_1_Larva_in_progress', 
     'player_1_Drone_live', 'player_1_Drone_dead', 'player_1_Drone_in_progress', 
     'player_1_Overlord_live', 'player_1_Overlord_dead', 'player_1_Overlord_in_progress', 
     'player_1_Hatchery_live', 'player_1_Hatchery_dead', 'player_1_Hatchery_in_progress', 
     'player_2_Egg_live', 'player_2_Egg_dead', 'player_2_Egg_in_progress', 
     'player_2_Larva_live', 'player_2_Larva_dead', 'player_2_Larva_in_progress', 
     'player_2_Drone_live', 'player_2_Drone_dead', 'player_2_Drone_in_progress', 
     'player_2_Overlord_live', 'player_2_Overlord_dead', 'player_2_Overlord_in_progress', 
     'player_2_Hatchery_live', 'player_2_Hatchery_dead', 'player_2_Hatchery_in_progress', 
     'player_1_Extractor_live', 'player_1_Extractor_dead', 'player_1_Extractor_in_progress', 
     'player_2_Extractor_live', 'player_2_Extractor_dead', 'player_2_Extractor_in_progress', 
     'player_1_SpawningPool_live', 'player_1_SpawningPool_dead', 'player_1_SpawningPool_in_progress', 
     'player_2_SpawningPool_live', 'player_2_SpawningPool_dead', 'player_2_SpawningPool_in_progress', 
     'player_1_Zergling_live', 'player_1_Zergling_dead', 'player_1_Zergling_in_progress', 
     'player_2_Zergling_live', 'player_2_Zergling_dead', 'player_2_Zergling_in_progress', 
     'player_1_Queen_live', 'player_1_Queen_dead', 'player_1_Queen_in_progress', 
     'player_2_Queen_live', 'player_2_Queen_dead', 'player_2_Queen_in_progress', 
     'player_2_BanelingNest_live', 'player_2_BanelingNest_dead', 'player_2_BanelingNest_in_progress', 
     'player_1_BanelingNest_live', 'player_1_BanelingNest_dead', 'player_1_BanelingNest_in_progress', 
     'player_2_CreepTumorQueen_live', 'player_2_CreepTumorQueen_dead', 'player_2_CreepTumorQueen_in_progress', 
     'player_1_ZerglingMovementSpeed', 
     'player_2_BanelingCocoon_live', 'player_2_BanelingCocoon_dead', 'player_2_BanelingCocoon_in_progress', 
     'player_2_ZerglingMovementSpeed', 
     'player_2_CreepTumorBurrowed_live', 'player_2_CreepTumorBurrowed_dead', 'player_2_CreepTumorBurrowed_in_progress', 
     'player_2_Baneling_live', 'player_2_Baneling_dead', 'player_2_Baneling_in_progress', 
     'player_1_RoachWarren_live', 'player_1_RoachWarren_dead', 'player_1_RoachWarren_in_progress', 
     'player_1_BanelingCocoon_live', 'player_1_BanelingCocoon_dead', 'player_1_BanelingCocoon_in_progress', 
     'player_2_RoachWarren_live', 'player_2_RoachWarren_dead', 'player_2_RoachWarren_in_progress', 
     'player_1_Baneling_live', 'player_1_Baneling_dead', 'player_1_Baneling_in_progress', 
     'player_2_EvolutionChamber_live', 'player_2_EvolutionChamber_dead', 'player_2_EvolutionChamber_in_progress', 
     'player_1_Roach_live', 'player_1_Roach_dead', 'player_1_Roach_in_progress', 
     'player_2_Roach_live', 'player_2_Roach_dead', 'player_2_Roach_in_progress', 
     'player_2_RavagerCocoon_live', 'player_2_RavagerCocoon_dead', 'player_2_RavagerCocoon_in_progress', 
     'player_2_Ravager_live', 'player_2_Ravager_dead', 'player_2_Ravager_in_progress', 
     'player_1_EvolutionChamber_live', 'player_1_EvolutionChamber_dead', 'player_1_EvolutionChamber_in_progress', 
     'player_1_RavagerCocoon_live', 'player_1_RavagerCocoon_dead', 'player_1_RavagerCocoon_in_progress', 
     'player_1_Ravager_live', 'player_1_Ravager_dead', 'player_1_Ravager_in_progress', 
     'player_2_SpineCrawler_live', 'player_2_SpineCrawler_dead', 'player_2_SpineCrawler_in_progress', 
     'player_2_ZergMissileWeaponsLevel1', 
     'player_2_CreepTumor_live', 'player_2_CreepTumor_dead', 'player_2_CreepTumor_in_progress', 
     'player_2_OverlordCocoon_live', 'player_2_OverlordCocoon_dead', 'player_2_OverlordCocoon_in_progress', 
     'player_2_Lair_live', 'player_2_Lair_dead', 'player_2_Lair_in_progress', 
     'player_2_Overseer_live', 'player_2_Overseer_dead', 'player_2_Overseer_in_progress', 
     'player_1_Lair_live', 'player_1_Lair_dead', 'player_1_Lair_in_progress', 
     'player_1_OverlordCocoon_live', 'player_1_OverlordCocoon_dead', 'player_1_OverlordCocoon_in_progress', 
     'player_1_Overseer_live', 'player_1_Overseer_dead', 'player_1_Overseer_in_progress', 
     'player_1_ZergGroundArmorsLevel1', 
     'player_2_OverlordSpeed', 
     'player_2_GlialReconstitution', 
     'player_1_GlialReconstitution', 
     'player_2_ZergMissileWeaponsLevel2', 
     'player_2_ZergGroundArmorsLevel1', 
     'player_2_OverseerSiegeMode_live', 'player_2_OverseerSiegeMode_dead', 'player_2_OverseerSiegeMode_in_progress', 
     'player_2_Burrow', 
     'player_2_TunnelingClaws', 
     'player_1_InfestationPit_live', 'player_1_InfestationPit_dead', 'player_1_InfestationPit_in_progress', 
     'player_1_ZergMissileWeaponsLevel1', 
     'player_2_InfestationPit_live', 'player_2_InfestationPit_dead', 
     'player_2_InfestationPit_in_progress', 
     'player_1_SpineCrawler_live', 'player_1_SpineCrawler_dead', 
     'player_1_SpineCrawler_in_progress', 
     'player_1_OverlordSpeed',
     'player_2_HydraliskDen_live', 'player_2_HydraliskDen_dead', 'player_2_HydraliskDen_in_progress', 
     'player_2_ZergGroundArmorsLevel2', 
     'player_2_LurkerDenMP_live', 'player_2_LurkerDenMP_dead', 'player_2_LurkerDenMP_in_progress', 
     'player_1_ZergMissileWeaponsLevel2', 
     'player_2_Hive_live', 'player_2_Hive_dead', 'player_2_Hive_in_progress', 
     'player_1_Hive_live', 'player_1_Hive_dead', 'player_1_Hive_in_progress', 
     'player_1_HydraliskDen_live', 'player_1_HydraliskDen_dead', 'player_1_HydraliskDen_in_progress', 
     'player_2_Hydralisk_live', 'player_2_Hydralisk_dead', 'player_2_Hydralisk_in_progress', 
     'player_2_LurkerMPEgg_live', 'player_2_LurkerMPEgg_dead', 'player_2_LurkerMPEgg_in_progress',
       'player_2_LurkerMP_live', 'player_2_LurkerMP_dead', 'player_2_LurkerMP_in_progress', 
       'player_1_LurkerDenMP_live', 'player_1_LurkerDenMP_dead', 'player_1_LurkerDenMP_in_progress', 
       'player_2_EvolveGroovedSpines', 
       'player_1_Burrow', 
       'player_2_LurkerMPBurrowed_live', 'player_2_LurkerMPBurrowed_dead', 'player_2_LurkerMPBurrowed_in_progress', 
       'player_2_LurkerRange', 
       'player_1_EvolveGroovedSpines', 
       'player_1_NydusNetwork_live', 'player_1_NydusNetwork_dead', 'player_1_NydusNetwork_in_progress', 
       'player_2_Viper_live', 'player_2_Viper_dead', 'player_2_Viper_in_progress', 
       'player_2_EvolveMuscularAugments', 
       'player_1_ZergGroundArmorsLevel2', 
       'player_1_SporeCrawler_live', 'player_1_SporeCrawler_dead', 'player_1_SporeCrawler_in_progress', 
       'player_2_SporeCrawler_live', 'player_2_SporeCrawler_dead', 'player_2_SporeCrawler_in_progress', 
       'player_1_Hydralisk_live', 'player_1_Hydralisk_dead', 'player_1_Hydralisk_in_progress', 
       'player_1_LurkerRange', 
       'player_2_ZergMissileWeaponsLevel3', 'player_2_ZergGroundArmorsLevel3', 
       'player_2_DiggingClaws', 
       'player_1_LurkerMPEgg_live', 'player_1_LurkerMPEgg_dead', 'player_1_LurkerMPEgg_in_progress', 
       'player_1_NydusCanal_live', 'player_1_NydusCanal_dead', 'player_1_NydusCanal_in_progress', 
       'player_1_ZergMissileWeaponsLevel3', 
       'player_1_LurkerMP_live', 'player_1_LurkerMP_dead', 'player_1_LurkerMP_in_progress', 
       'player_1_LurkerMPBurrowed_live', 'player_1_LurkerMPBurrowed_dead', 'player_1_LurkerMPBurrowed_in_progress', 
       'player_1_Broodling_live', 'player_1_Broodling_dead', 'player_1_Broodling_in_progress', 
       'player_1_OverseerSiegeMode_live', 'player_1_OverseerSiegeMode_dead', 'player_1_OverseerSiegeMode_in_progress', 
       'player_1_CreepTumorQueen_live', 'player_1_CreepTumorQueen_dead', 'player_1_CreepTumorQueen_in_progress', 
       'player_1_CreepTumorBurrowed_live', 'player_1_CreepTumorBurrowed_dead', 'player_1_CreepTumorBurrowed_in_progress', 
       'player_1_CreepTumor_live', 'player_1_CreepTumor_dead', 'player_1_CreepTumor_in_progress',
         'player_2_Spire_live', 'player_2_Spire_dead', 'player_2_Spire_in_progress',
           'player_1_Spire_live', 'player_1_Spire_dead', 'player_1_Spire_in_progress', 
           'player_1_Mutalisk_live', 'player_1_Mutalisk_dead', 'player_1_Mutalisk_in_progress', 
           'player_2_Mutalisk_live', 'player_2_Mutalisk_dead', 'player_2_Mutalisk_in_progress', 
           'player_2_ZergFlyerWeaponsLevel1', 
           'player_1_TransportOverlordCocoon_live', 'player_1_TransportOverlordCocoon_dead', 'player_1_TransportOverlordCocoon_in_progress', 
           'player_1_OverlordTransport_live', 'player_1_OverlordTransport_dead', 'player_1_OverlordTransport_in_progress', 
           'player_2_CentrificalHooks', 
           'player_1_EvolveMuscularAugments', 
           'player_1_Infestor_live', 'player_1_Infestor_dead', 'player_1_Infestor_in_progress', 
           'player_2_Broodling_live', 'player_2_Broodling_dead', 'player_2_Broodling_in_progress', 
           'player_1_Viper_live', 'player_1_Viper_dead', 'player_1_Viper_in_progress', 
           'player_2_TransportOverlordCocoon_live', 'player_2_TransportOverlordCocoon_dead', 'player_2_TransportOverlordCocoon_in_progress', 
           'player_2_OverlordTransport_live', 'player_2_OverlordTransport_dead', 
           'player_2_OverlordTransport_in_progress', 
           'player_2_ZergMeleeWeaponsLevel1', 
           'player_1_TunnelingClaws', 
           'player_2_ZergMeleeWeaponsLevel2', 
           'player_2_ZergFlyerWeaponsLevel2', 
           'player_2_UltraliskCavern_live', 'player_2_UltraliskCavern_dead', 'player_2_UltraliskCavern_in_progress', 
           'player_2_ZergFlyerArmorsLevel1', 
           'player_1_DiggingClaws', 
           'player_2_ZerglingAttackSpeed', 
           'player_1_ZergMeleeWeaponsLevel1', 
           'player_1_ZergFlyerWeaponsLevel1', 
           'player_2_InfestorEnergyUpgrade', 
           'player_2_Infestor_live', 'player_2_Infestor_dead', 'player_2_Infestor_in_progress', 
           'player_1_ZergFlyerWeaponsLevel2', 
           'player_2_NydusNetwork_live', 'player_2_NydusNetwork_dead', 'player_2_NydusNetwork_in_progress', 
           'player_2_NydusCanal_live', 'player_2_NydusCanal_dead', 'player_2_NydusCanal_in_progress', 
           'player_2_ZergFlyerWeaponsLevel3', 'player_2_ChitinousPlating', 'player_1_ZergMeleeWeaponsLevel2', 
           'player_1_CentrificalHooks', 
           'player_1_UltraliskCavern_live', 'player_1_UltraliskCavern_dead', 'player_1_UltraliskCavern_in_progress', 
           'player_1_ZergFlyerArmorsLevel1', 'player_1_ZergFlyerArmorsLevel2', 'player_1_ZergFlyerWeaponsLevel3', 
           'player_1_Ultralisk_live', 'player_1_Ultralisk_dead', 'player_1_Ultralisk_in_progress', 
           'player_1_Corruptor_live', 'player_1_Corruptor_dead', 'player_1_Corruptor_in_progress',  
           'player_1_GreaterSpire_live', 'player_1_GreaterSpire_dead', 'player_1_GreaterSpire_in_progress', 
           'player_1_ZerglingAttackSpeed', 
           'player_1_ZergMeleeWeaponsLevel3', 
           'player_1_NeuralParasite', 
           'player_1_BroodLordCocoon_live', 'player_1_BroodLordCocoon_dead', 'player_1_BroodLordCocoon_in_progress', 
           'player_1_BroodLord_live', 'player_1_BroodLord_dead', 'player_1_BroodLord_in_progress', 
           'player_1_BroodlingEscort_live', 'player_1_BroodlingEscort_dead', 'player_1_BroodlingEscort_in_progress', 
             'player_2_Corruptor_live', 'player_2_Corruptor_dead', 'player_2_Corruptor_in_progress', 
             'player_2_GreaterSpire_live', 'player_2_GreaterSpire_dead', 'player_2_GreaterSpire_in_progress', 
             'player_2_BroodLordCocoon_live', 'player_2_BroodLordCocoon_dead', 'player_2_BroodLordCocoon_in_progress',
               'player_2_ZergMeleeWeaponsLevel3', 
               'player_2_BroodLord_live', 'player_2_BroodLord_dead', 'player_2_BroodLord_in_progress', 
               'player_2_BroodlingEscort_live', 'player_2_BroodlingEscort_dead', 'player_2_BroodlingEscort_in_progress',  
               'player_1_ZergGroundArmorsLevel3', 'player_2_SwarmHostMP_live', 'player_2_SwarmHostMP_dead', 
               'player_2_SwarmHostMP_in_progress', 
               'player_1_SwarmHostMP_live', 'player_1_SwarmHostMP_dead', 'player_1_SwarmHostMP_in_progress', 
               'player_1_LocustMPFlying_live', 'player_1_LocustMPFlying_dead', 'player_1_LocustMPFlying_in_progress', 
               'player_1_LocustMP_live', 'player_1_LocustMP_dead', 'player_1_LocustMP_in_progress', 
               'player_1_LocustMPPrecursor_live', 'player_1_LocustMPPrecursor_dead', 'player_1_LocustMPPrecursor_in_progress']