pvp = ['player_1_Protoss_mineral_collection_rate', 
       'player_1_Protoss_gas_collection_rate', 
       'player_1_Protoss_unspent_minerals', 
       'player_1_Protoss_unspent_gas', 
       'player_2_Protoss_mineral_collection_rate', 
       'player_2_Protoss_gas_collection_rate', 
       'player_2_Protoss_unspent_minerals', 
       'player_2_Protoss_unspent_gas', 
       'result', 
       'loop', 
       'player_1_Probe_live', 
       'player_1_Probe_dead', 
       'player_1_Probe_in_progress', 
       'player_1_Nexus_live', 
       'player_1_Nexus_dead', 
       'player_1_Nexus_in_progress', 
       'player_2_Probe_live', 
       'player_2_Probe_dead', 
       'player_2_Probe_in_progress', 
       'player_2_Nexus_live', 
       'player_2_Nexus_dead', 
       'player_2_Nexus_in_progress', 
       'player_1_Pylon_live', 
       'player_1_Pylon_dead', 
       'player_1_Pylon_in_progress', 
       'player_2_Pylon_live', 
       'player_2_Pylon_dead', 
       'player_2_Pylon_in_progress', 
       'player_1_Gateway_live', 'player_1_Gateway_dead', 'player_1_Gateway_in_progress', 
       'player_2_Gateway_live', 'player_2_Gateway_dead', 'player_2_Gateway_in_progress', 
       'player_1_Assimilator_live', 'player_1_Assimilator_dead', 'player_1_Assimilator_in_progress', 
       'player_2_Assimilator_live', 'player_2_Assimilator_dead', 'player_2_Assimilator_in_progress', 
       'player_1_CyberneticsCore_live', 'player_1_CyberneticsCore_dead', 'player_1_CyberneticsCore_in_progress', 
       'player_2_CyberneticsCore_live', 'player_2_CyberneticsCore_dead', 'player_2_CyberneticsCore_in_progress', 
       'player_1_Sentry_live', 'player_1_Sentry_dead', 'player_1_Sentry_in_progress', 
       'player_1_Stalker_live', 'player_1_Stalker_dead', 'player_1_Stalker_in_progress', 
       'player_2_Stalker_live', 'player_2_Stalker_dead', 'player_2_Stalker_in_progress', 
       'player_1_Phoenix_live', 'player_1_Phoenix_dead', 'player_1_Phoenix_in_progress', 
       'player_2_ShieldBattery_live', 'player_2_ShieldBattery_dead', 'player_2_ShieldBattery_in_progress', 
       'player_1_TwilightCouncil_live', 'player_1_TwilightCouncil_dead', 'player_1_TwilightCouncil_in_progress', 
       'player_1_RoboticsFacility_live', 'player_1_RoboticsFacility_dead', 'player_1_RoboticsFacility_in_progress', 
       'player_2_WarpGateResearch', 'player_1_WarpGateResearch', 
       'player_2_WarpGate_live', 'player_2_WarpGate_dead', 'player_2_WarpGate_in_progress', 
       'player_1_Zealot_live', 'player_1_Zealot_dead', 'player_1_Zealot_in_progress', 
       'player_1_WarpGate_live', 'player_1_WarpGate_dead', 'player_1_WarpGate_in_progress', 
       'player_1_ShieldBattery_live', 'player_1_ShieldBattery_dead', 'player_1_ShieldBattery_in_progress', 
       'player_2_Sentry_live', 'player_2_Sentry_dead', 'player_2_Sentry_in_progress', 
       'player_1_Immortal_live', 'player_1_Immortal_dead', 'player_1_Immortal_in_progress', 
       'player_1_Adept_live', 'player_1_Adept_dead', 'player_1_Adept_in_progress', 
       'player_2_Zealot_live', 'player_2_Zealot_dead', 'player_2_Zealot_in_progress', 
       'player_1_WarpPrism_live', 'player_1_WarpPrism_dead', 'player_1_WarpPrism_in_progress', 
       'player_1_Observer_live', 'player_1_Observer_dead', 'player_1_Observer_in_progress', 
       'player_2_Adept_live', 'player_2_Adept_dead', 'player_2_Adept_in_progress', 'player_2_Stargate_live', 
       'player_2_Stargate_dead', 'player_2_Stargate_in_progress', 'player_2_RoboticsFacility_live', 
       'player_2_RoboticsFacility_dead', 'player_2_RoboticsFacility_in_progress', 'player_1_WarpPrismPhasing_live', 
       'player_1_WarpPrismPhasing_dead', 'player_1_WarpPrismPhasing_in_progress', 
       'player_1_Forge_live', 'player_1_Forge_dead', 'player_1_Forge_in_progress', 
       'player_2_Phoenix_live', 'player_2_Phoenix_dead', 'player_2_Phoenix_in_progress', 
       'player_2_Observer_live', 'player_2_Observer_dead', 'player_2_Observer_in_progress', 
       'player_2_RoboticsBay_live', 'player_2_RoboticsBay_dead', 'player_2_RoboticsBay_in_progress', 
       'player_2_Immortal_live', 'player_2_Immortal_dead', 'player_2_Immortal_in_progress', 
       'player_2_ObserverSiegeMode_live', 'player_2_ObserverSiegeMode_dead', 'player_2_ObserverSiegeMode_in_progress', 
       'player_1_PhotonCannon_live', 'player_1_PhotonCannon_dead', 'player_1_PhotonCannon_in_progress', 
       'player_1_BlinkTech', 'player_2_Oracle_live', 'player_2_Oracle_dead', 'player_2_Oracle_in_progress', 
       'player_2_Disruptor_live', 'player_2_Disruptor_dead', 'player_2_Disruptor_in_progress', 
       'player_1_ObserverSiegeMode_live', 'player_1_ObserverSiegeMode_dead', 'player_1_ObserverSiegeMode_in_progress', 
       'player_1_ProtossGroundWeaponsLevel1', 'player_1_Stargate_live', 'player_1_Stargate_dead', 
       'player_1_Stargate_in_progress', 'player_2_TwilightCouncil_live', 'player_2_TwilightCouncil_dead', 
       'player_2_TwilightCouncil_in_progress', 'player_1_Oracle_live', 'player_1_Oracle_dead', 
       'player_1_Oracle_in_progress', 'player_1_DarkShrine_live', 'player_1_DarkShrine_dead', 
       'player_1_DarkShrine_in_progress', 'player_1_DarkTemplar_live', 'player_1_DarkTemplar_dead', 
       'player_1_DarkTemplar_in_progress', 'player_2_BlinkTech', 'player_2_WarpPrism_live', 
       'player_2_WarpPrism_dead', 'player_2_WarpPrism_in_progress', 'player_2_WarpPrismPhasing_live', 
       'player_2_WarpPrismPhasing_dead', 'player_2_WarpPrismPhasing_in_progress', 
       'player_2_Forge_live', 'player_2_Forge_dead', 'player_2_Forge_in_progress', 
       'player_1_Charge', 
       'player_1_RoboticsBay_live', 'player_1_RoboticsBay_dead', 'player_1_RoboticsBay_in_progress', 
       'player_2_HighTemplar_live', 'player_2_HighTemplar_dead', 'player_2_HighTemplar_in_progress', 
       'player_2_PhotonCannon_live', 'player_2_PhotonCannon_dead', 'player_2_PhotonCannon_in_progress', 
       'player_1_HighTemplar_live', 'player_1_HighTemplar_dead', 'player_1_HighTemplar_in_progress', 
       'player_2_Archon_live', 'player_2_Archon_dead', 'player_2_Archon_in_progress', 
       'player_1_Archon_live', 'player_1_Archon_dead', 'player_1_Archon_in_progress', 
       'player_2_ProtossGroundWeaponsLevel1', 
       'player_2_Charge', 
       'player_1_Disruptor_live', 'player_1_Disruptor_dead', 'player_1_Disruptor_in_progress', 
       'player_1_ProtossGroundWeaponsLevel2', 
       'player_2_DarkShrine_live', 
       'player_2_DarkShrine_dead', 
       'player_2_DarkShrine_in_progress', 
       'player_2_ProtossGroundWeaponsLevel2', 
       'player_1_Colossus_live', 'player_1_Colossus_dead', 'player_1_Colossus_in_progress', 
       'player_2_DarkTemplar_live', 'player_2_DarkTemplar_dead', 'player_2_DarkTemplar_in_progress', 
       'player_1_ProtossGroundWeaponsLevel3', 
       'player_2_DarkTemplarBlinkUpgrade', 
       'player_2_ProtossGroundWeaponsLevel3', 
       'player_1_AdeptPiercingAttack', 
       'player_2_ProtossShieldsLevel1', 
       'player_1_ProtossShieldsLevel1', 
       'player_1_ObserverGraviticBooster', 
       'player_2_ProtossShieldsLevel2', 
       'player_2_ObserverGraviticBooster', 
       'player_2_GraviticDrive', 
       'player_1_ProtossGroundArmorsLevel1', 
       'player_1_DarkTemplarBlinkUpgrade', 
       'player_2_ProtossGroundArmorsLevel1', 
       'player_1_GraviticDrive', 
       'player_1_ProtossAirWeaponsLevel1', 
       'player_2_AdeptPiercingAttack',
       'player_2_FleetBeacon_live', 'player_2_FleetBeacon_dead', 'player_2_FleetBeacon_in_progress', 
       'player_1_FleetBeacon_live', 'player_1_FleetBeacon_dead', 'player_1_FleetBeacon_in_progress', 
       'player_2_Tempest_live', 'player_2_Tempest_dead', 'player_2_Tempest_in_progress', 
       'player_2_ProtossAirWeaponsLevel1', 
       'player_1_Carrier_live', 'player_1_Carrier_dead', 'player_1_Carrier_in_progress', 
       'player_1_Interceptor_live', 'player_1_Interceptor_dead', 'player_1_Interceptor_in_progress', 
       'player_1_Tempest_live', 'player_1_Tempest_dead', 'player_1_Tempest_in_progress', 
       'player_2_ProtossAirWeaponsLevel2', 
       'player_1_ProtossAirWeaponsLevel2', 
       'player_2_Mothership_live', 
       'player_2_Mothership_dead', 
       'player_2_Mothership_in_progress', 
       'player_2_ProtossAirWeaponsLevel3', 
       'player_2_Carrier_live', 
       'player_2_Carrier_dead', 
       'player_2_Carrier_in_progress', 
       'player_2_Interceptor_live', 
       'player_2_Interceptor_dead', 
       'player_2_Interceptor_in_progress', 
       'player_1_ProtossGroundArmorsLevel2', 
       'player_2_Colossus_live', 'player_2_Colossus_dead', 'player_2_Colossus_in_progress', 
       'player_1_VoidRay_live', 'player_1_VoidRay_dead', 'player_1_VoidRay_in_progress', 
       'player_2_ProtossGroundArmorsLevel2', 
       'player_1_ProtossShieldsLevel2', 
       'player_1_ProtossAirWeaponsLevel3', 
       'player_1_ProtossShieldsLevel3', 
       'player_1_ProtossAirArmorsLevel1', 
       'player_2_VoidRay_live', 'player_2_VoidRay_dead', 'player_2_VoidRay_in_progress', 
       'player_2_ProtossGroundArmorsLevel3', 
       'player_2_PsiStormTech', 'player_1_PsiStormTech', 
       'player_1_Mothership_live', 'player_1_Mothership_dead', 'player_1_Mothership_in_progress', 
       'player_2_ProtossAirArmorsLevel1', 
       'player_1_ProtossAirArmorsLevel2', 
       'player_2_ProtossAirArmorsLevel2', 
       'player_2_ProtossShieldsLevel3', 
       'player_1_ProtossAirArmorsLevel3', 
       'player_2_ProtossAirArmorsLevel3',  
       'player_2_PhoenixRangeUpgrade', 
       'player_1_ExtendedThermalLance', 
       'player_1_ProtossGroundArmorsLevel3', 
       'player_2_ExtendedThermalLance', 
       'player_1_PhoenixRangeUpgrade']

pvt = ['Protoss_mineral_collection_rate', 'Protoss_gas_collection_rate', 
       'Protoss_unspent_minerals', 'Protoss_unspent_gas', 
       'Terran_mineral_collection_rate', 'Terran_gas_collection_rate', 
       'Terran_unspent_minerals', 'Terran_unspent_gas', 
       'result', 
       'loop', 
       'Probe_live', 'Probe_dead', 'Probe_in_progress', 
       'Nexus_live', 'Nexus_dead', 'Nexus_in_progress', 
       'SCV_live', 'SCV_dead', 'SCV_in_progress', 
       'CommandCenter_live', 'CommandCenter_dead', 'CommandCenter_in_progress', 
       'Pylon_live', 'Pylon_dead', 'Pylon_in_progress', 
       'SupplyDepot_live', 'SupplyDepot_dead', 'SupplyDepot_in_progress', 
       'Refinery_live', 'Refinery_dead', 'Refinery_in_progress', 
       'Gateway_live', 'Gateway_dead', 'Gateway_in_progress', 
       'Assimilator_live', 'Assimilator_dead', 'Assimilator_in_progress', 
       'Barracks_live', 'Barracks_dead', 'Barracks_in_progress', 
       'CyberneticsCore_live', 'CyberneticsCore_dead', 'CyberneticsCore_in_progress', 
       'OrbitalCommand_live', 'OrbitalCommand_dead', 'OrbitalCommand_in_progress', 
       'Factory_live', 'Factory_dead', 'Factory_in_progress', 
       'MULE_live', 'MULE_dead', 'MULE_in_progress', 
       'SupplyDepotLowered_live', 'SupplyDepotLowered_dead', 'SupplyDepotLowered_in_progress', 
       'Reaper_live', 'Reaper_dead', 'Reaper_in_progress', 
       'BarracksReactor_live', 'BarracksReactor_dead', 'BarracksReactor_in_progress', 
       'Adept_live', 'Adept_dead', 'Adept_in_progress', 
       'TwilightCouncil_live', 'TwilightCouncil_dead', 'TwilightCouncil_in_progress', 
       'FactoryTechLab_live', 'FactoryTechLab_dead', 'FactoryTechLab_in_progress', 
       'Starport_live', 'Starport_dead', 'Starport_in_progress', 
       'Stalker_live', 'Stalker_dead', 'Stalker_in_progress', 
       'Marine_live', 'Marine_dead', 'Marine_in_progress', 
       'DarkShrine_live', 'DarkShrine_dead', 'DarkShrine_in_progress', 
       'WarpGateResearch', 
       'Cyclone_live', 'Cyclone_dead', 'Cyclone_in_progress', 
       'WarpGate_live', 'WarpGate_dead', 'WarpGate_in_progress', 
       'OrbitalCommandFlying_live', 'OrbitalCommandFlying_dead', 'OrbitalCommandFlying_in_progress', 
       'Medivac_live', 'Medivac_dead', 'Medivac_in_progress', 
       'RoboticsFacility_live', 'RoboticsFacility_dead', 'RoboticsFacility_in_progress', 
       'StarportTechLab_live', 'StarportTechLab_dead', 'StarportTechLab_in_progress', 
       'ShieldBattery_live', 'ShieldBattery_dead', 'ShieldBattery_in_progress', 
       'DarkTemplar_live', 'DarkTemplar_dead', 'DarkTemplar_in_progress', 
       'EngineeringBay_live', 'EngineeringBay_dead', 'EngineeringBay_in_progress', 
       'SiegeTank_live', 'SiegeTank_dead', 'SiegeTank_in_progress', 
       'Observer_live', 'Observer_dead', 'Observer_in_progress', 
       'Sentry_live', 'Sentry_dead', 'Sentry_in_progress', 
       'Raven_live', 'Raven_dead', 'Raven_in_progress', 
       'Immortal_live', 'Immortal_dead', 'Immortal_in_progress', 
       'MissileTurret_live', 'MissileTurret_dead', 'MissileTurret_in_progress', 
       'StarportFlying_live', 'StarportFlying_dead', 'StarportFlying_in_progress', 
       'BarracksFlying_live', 'BarracksFlying_dead', 'BarracksFlying_in_progress', 
       'BarracksTechLab_live', 'BarracksTechLab_dead', 'BarracksTechLab_in_progress', 
       'StarportReactor_live', 'StarportReactor_dead', 'StarportReactor_in_progress', 
       'Charge', 
       'Archon_live', 'Archon_dead', 'Archon_in_progress', 
       'SiegeTankSieged_live', 'SiegeTankSieged_dead', 'SiegeTankSieged_in_progress', 
       'Zealot_live', 'Zealot_dead', 'Zealot_in_progress', 
       'WarpPrism_live', 'WarpPrism_dead', 'WarpPrism_in_progress', 
       'AutoTurret_live', 'AutoTurret_dead', 'AutoTurret_in_progress', 
       'TerranInfantryWeaponsLevel1', 
       'WarpPrismPhasing_live', 'WarpPrismPhasing_dead', 'WarpPrismPhasing_in_progress', 
       'FactoryFlying_live', 'FactoryFlying_dead', 'FactoryFlying_in_progress', 
       'Forge_live', 'Forge_dead', 'Forge_in_progress', 
       'Phoenix_live', 'Phoenix_dead', 'Phoenix_in_progress', 
       'FactoryReactor_live', 'FactoryReactor_dead', 'FactoryReactor_in_progress', 
       'Stimpack', 
       'Armory_live', 'Armory_dead', 'Armory_in_progress', 
       'WidowMine_live', 'WidowMine_dead', 'WidowMine_in_progress', 
       'Marauder_live', 'Marauder_dead', 'Marauder_in_progress', 
       'BlinkTech', 
       'GhostAcademy_live', 'GhostAcademy_dead', 'GhostAcademy_in_progress', 
       'TerranInfantryArmorsLevel1', 
       'WidowMineBurrowed_live', 'WidowMineBurrowed_dead', 'WidowMineBurrowed_in_progress', 
       'ProtossGroundWeaponsLevel1', 
       'RoboticsBay_live', 'RoboticsBay_dead', 'RoboticsBay_in_progress', 
       'Ghost_live', 'Ghost_dead', 'Ghost_in_progress', 
       'PunisherGrenades', 'ObserverSiegeMode_live', 'ObserverSiegeMode_dead', 
       'ObserverSiegeMode_in_progress', 
       'Colossus_live', 'Colossus_dead', 'Colossus_in_progress', 
       'SensorTower_live', 'SensorTower_dead', 'SensorTower_in_progress', 
       'ProtossGroundWeaponsLevel2', 
       'VikingFighter_live', 'VikingFighter_dead', 'VikingFighter_in_progress', 
       'EnhancedShockwaves', 
       'PhotonCannon_live', 'PhotonCannon_dead', 'PhotonCannon_in_progress', 
       'ExtendedThermalLance', 
       'Disruptor_live', 'Disruptor_dead', 'Disruptor_in_progress', 
       'TerranInfantryWeaponsLevel2', 
       'ProtossGroundArmorsLevel1', 
       'DarkTemplarBlinkUpgrade', 
       'CommandCenterFlying_live', 'CommandCenterFlying_dead', 'CommandCenterFlying_in_progress', 
       'GraviticDrive', 
       'PlanetaryFortress_live', 'PlanetaryFortress_dead', 'PlanetaryFortress_in_progress', 
       'TerranShipWeaponsLevel1', 
       'ProtossGroundWeaponsLevel3', 
       'Hellion_live', 'Hellion_dead', 'Hellion_in_progress', 
       'Bunker_live', 'Bunker_dead', 'Bunker_in_progress', 
       'Stargate_live', 'Stargate_dead', 'Stargate_in_progress', 
       'VoidRay_live', 'VoidRay_dead', 'VoidRay_in_progress', 
       'HighTemplar_live', 'HighTemplar_dead', 'HighTemplar_in_progress', 
       'PsiStormTech', 
       'Liberator_live', 'Liberator_dead', 'Liberator_in_progress', 
       'LiberatorAG_live', 'LiberatorAG_dead', 'LiberatorAG_in_progress', 
       'TerranInfantryArmorsLevel2', 
       'VikingAssault_live', 'VikingAssault_dead', 'VikingAssault_in_progress', 
       'ProtossGroundArmorsLevel2', 'TerranInfantryWeaponsLevel3', 'TerranInfantryArmorsLevel3', 
       'ProtossGroundArmorsLevel3', 'TerranShipWeaponsLevel2', 
       'FusionCore_live', 'FusionCore_dead', 'FusionCore_in_progress', 
       'PersonalCloaking', 
       'LiberatorAGRangeUpgrade', 
       'TerranShipWeaponsLevel3', 
       'Oracle_live', 'Oracle_dead', 'Oracle_in_progress', 
       'Banshee_live', 'Banshee_dead', 'Banshee_in_progress', 
       'BansheeCloak', 
       'TerranVehicleWeaponsLevel1', 
       'FleetBeacon_live', 'FleetBeacon_dead', 'FleetBeacon_in_progress', 
       'ObserverGraviticBooster', 
       'ProtossAirWeaponsLevel1', 
       'HiSecAutoTracking', 
       'TerranBuildingArmor', 
       'MedivacIncreaseSpeedBoost', 
       'ProtossShieldsLevel1', 
       'Carrier_live', 'Carrier_dead', 'Carrier_in_progress', 
       'Interceptor_live', 'Interceptor_dead', 'Interceptor_in_progress', 
       'Tempest_live', 'Tempest_dead', 'Tempest_in_progress', 
       'SmartServos', 
       'ProtossAirWeaponsLevel2', 
       'ProtossAirArmorsLevel1', 
       'ProtossAirArmorsLevel2', 
       'ProtossAirWeaponsLevel3', 
       'ProtossShieldsLevel2', 
       'Mothership_live', 'Mothership_dead', 'Mothership_in_progress', 
       'TerranVehicleAndShipArmorsLevel1', 
       'PhoenixRangeUpgrade', 
       'TerranVehicleAndShipArmorsLevel2', 
       'ProtossShieldsLevel3', 
       'DrillClaws', 
       'TerranVehicleAndShipArmorsLevel3', 
       'ProtossAirArmorsLevel3', 
       'TerranVehicleWeaponsLevel2', 
       'TerranVehicleWeaponsLevel3', 
       'Thor_live', 'Thor_dead', 'Thor_in_progress', 
       'ThorAP_live', 'ThorAP_dead', 'ThorAP_in_progress', 
       'AdeptPiercingAttack', 
       'Battlecruiser_live', 'Battlecruiser_dead', 'Battlecruiser_in_progress', 
       'BattlecruiserEnableSpecializations', 
       'CycloneLockOnDamageUpgrade', 'HellionTank_live', 'HellionTank_dead', 'HellionTank_in_progress']