pvp = ['player_1_Protoss_mineral_collection_rate', 
       'player_1_Protoss_gas_collection_rate', 
       'player_1_Protoss_unspent_minerals', 
       'player_1_Protoss_unspent_gas', 
       'player_2_Protoss_mineral_collection_rate', 
       'player_2_Protoss_gas_collection_rate', 
       'player_2_Protoss_unspent_minerals', 
       'player_2_Protoss_unspent_gas', 
       'result', 
       'loop', 
       'player_1_Probe_live', 
       'player_1_Probe_dead', 
       'player_1_Probe_in_progress', 
       'player_1_Nexus_live', 
       'player_1_Nexus_dead', 
       'player_1_Nexus_in_progress', 
       'player_2_Probe_live', 
       'player_2_Probe_dead', 
       'player_2_Probe_in_progress', 
       'player_2_Nexus_live', 
       'player_2_Nexus_dead', 
       'player_2_Nexus_in_progress', 
       'player_1_Pylon_live', 
       'player_1_Pylon_dead', 
       'player_1_Pylon_in_progress', 
       'player_2_Pylon_live', 
       'player_2_Pylon_dead', 
       'player_2_Pylon_in_progress', 
       'player_1_Gateway_live', 'player_1_Gateway_dead', 'player_1_Gateway_in_progress', 
       'player_2_Gateway_live', 'player_2_Gateway_dead', 'player_2_Gateway_in_progress', 
       'player_1_Assimilator_live', 'player_1_Assimilator_dead', 'player_1_Assimilator_in_progress', 
       'player_2_Assimilator_live', 'player_2_Assimilator_dead', 'player_2_Assimilator_in_progress', 
       'player_1_CyberneticsCore_live', 'player_1_CyberneticsCore_dead', 'player_1_CyberneticsCore_in_progress', 
       'player_2_CyberneticsCore_live', 'player_2_CyberneticsCore_dead', 'player_2_CyberneticsCore_in_progress', 
       'player_1_Sentry_live', 'player_1_Sentry_dead', 'player_1_Sentry_in_progress', 
       'player_1_Stalker_live', 'player_1_Stalker_dead', 'player_1_Stalker_in_progress', 
       'player_2_Stalker_live', 'player_2_Stalker_dead', 'player_2_Stalker_in_progress', 
       'player_1_Phoenix_live', 'player_1_Phoenix_dead', 'player_1_Phoenix_in_progress', 
       'player_2_ShieldBattery_live', 'player_2_ShieldBattery_dead', 'player_2_ShieldBattery_in_progress', 
       'player_1_TwilightCouncil_live', 'player_1_TwilightCouncil_dead', 'player_1_TwilightCouncil_in_progress', 
       'player_1_RoboticsFacility_live', 'player_1_RoboticsFacility_dead', 'player_1_RoboticsFacility_in_progress', 
       'player_2_WarpGateResearch', 'player_1_WarpGateResearch', 
       'player_2_WarpGate_live', 'player_2_WarpGate_dead', 'player_2_WarpGate_in_progress', 
       'player_1_Zealot_live', 'player_1_Zealot_dead', 'player_1_Zealot_in_progress', 
       'player_1_WarpGate_live', 'player_1_WarpGate_dead', 'player_1_WarpGate_in_progress', 
       'player_1_ShieldBattery_live', 'player_1_ShieldBattery_dead', 'player_1_ShieldBattery_in_progress', 
       'player_2_Sentry_live', 'player_2_Sentry_dead', 'player_2_Sentry_in_progress', 
       'player_1_Immortal_live', 'player_1_Immortal_dead', 'player_1_Immortal_in_progress', 
       'player_1_Adept_live', 'player_1_Adept_dead', 'player_1_Adept_in_progress', 
       'player_2_Zealot_live', 'player_2_Zealot_dead', 'player_2_Zealot_in_progress', 
       'player_1_WarpPrism_live', 'player_1_WarpPrism_dead', 'player_1_WarpPrism_in_progress', 
       'player_1_Observer_live', 'player_1_Observer_dead', 'player_1_Observer_in_progress', 
       'player_2_Adept_live', 'player_2_Adept_dead', 'player_2_Adept_in_progress', 'player_2_Stargate_live', 
       'player_2_Stargate_dead', 'player_2_Stargate_in_progress', 'player_2_RoboticsFacility_live', 
       'player_2_RoboticsFacility_dead', 'player_2_RoboticsFacility_in_progress', 'player_1_WarpPrismPhasing_live', 
       'player_1_WarpPrismPhasing_dead', 'player_1_WarpPrismPhasing_in_progress', 
       'player_1_Forge_live', 'player_1_Forge_dead', 'player_1_Forge_in_progress', 
       'player_2_Phoenix_live', 'player_2_Phoenix_dead', 'player_2_Phoenix_in_progress', 
       'player_2_Observer_live', 'player_2_Observer_dead', 'player_2_Observer_in_progress', 
       'player_2_RoboticsBay_live', 'player_2_RoboticsBay_dead', 'player_2_RoboticsBay_in_progress', 
       'player_2_Immortal_live', 'player_2_Immortal_dead', 'player_2_Immortal_in_progress', 
       'player_2_ObserverSiegeMode_live', 'player_2_ObserverSiegeMode_dead', 'player_2_ObserverSiegeMode_in_progress', 
       'player_1_PhotonCannon_live', 'player_1_PhotonCannon_dead', 'player_1_PhotonCannon_in_progress', 
       'player_1_BlinkTech', 'player_2_Oracle_live', 'player_2_Oracle_dead', 'player_2_Oracle_in_progress', 
       'player_2_Disruptor_live', 'player_2_Disruptor_dead', 'player_2_Disruptor_in_progress', 
       'player_1_ObserverSiegeMode_live', 'player_1_ObserverSiegeMode_dead', 'player_1_ObserverSiegeMode_in_progress', 
       'player_1_ProtossGroundWeaponsLevel1', 'player_1_Stargate_live', 'player_1_Stargate_dead', 
       'player_1_Stargate_in_progress', 'player_2_TwilightCouncil_live', 'player_2_TwilightCouncil_dead', 
       'player_2_TwilightCouncil_in_progress', 'player_1_Oracle_live', 'player_1_Oracle_dead', 
       'player_1_Oracle_in_progress', 'player_1_DarkShrine_live', 'player_1_DarkShrine_dead', 
       'player_1_DarkShrine_in_progress', 'player_1_DarkTemplar_live', 'player_1_DarkTemplar_dead', 
       'player_1_DarkTemplar_in_progress', 'player_2_BlinkTech', 'player_2_WarpPrism_live', 
       'player_2_WarpPrism_dead', 'player_2_WarpPrism_in_progress', 'player_2_WarpPrismPhasing_live', 
       'player_2_WarpPrismPhasing_dead', 'player_2_WarpPrismPhasing_in_progress', 
       'player_2_Forge_live', 'player_2_Forge_dead', 'player_2_Forge_in_progress', 
       'player_1_Charge', 
       'player_1_RoboticsBay_live', 'player_1_RoboticsBay_dead', 'player_1_RoboticsBay_in_progress', 
       'player_2_HighTemplar_live', 'player_2_HighTemplar_dead', 'player_2_HighTemplar_in_progress', 
       'player_2_PhotonCannon_live', 'player_2_PhotonCannon_dead', 'player_2_PhotonCannon_in_progress', 
       'player_1_HighTemplar_live', 'player_1_HighTemplar_dead', 'player_1_HighTemplar_in_progress', 
       'player_2_Archon_live', 'player_2_Archon_dead', 'player_2_Archon_in_progress', 
       'player_1_Archon_live', 'player_1_Archon_dead', 'player_1_Archon_in_progress', 
       'player_2_ProtossGroundWeaponsLevel1', 
       'player_2_Charge', 
       'player_1_Disruptor_live', 'player_1_Disruptor_dead', 'player_1_Disruptor_in_progress', 
       'player_1_ProtossGroundWeaponsLevel2', 
       'player_2_DarkShrine_live', 
       'player_2_DarkShrine_dead', 
       'player_2_DarkShrine_in_progress', 
       'player_2_ProtossGroundWeaponsLevel2', 
       'player_1_Colossus_live', 'player_1_Colossus_dead', 'player_1_Colossus_in_progress', 
       'player_2_DarkTemplar_live', 'player_2_DarkTemplar_dead', 'player_2_DarkTemplar_in_progress', 
       'player_1_ProtossGroundWeaponsLevel3', 
       'player_2_DarkTemplarBlinkUpgrade', 
       'player_2_ProtossGroundWeaponsLevel3', 
       'player_1_AdeptPiercingAttack', 
       'player_2_ProtossShieldsLevel1', 
       'player_1_ProtossShieldsLevel1', 
       'player_1_ObserverGraviticBooster', 
       'player_2_ProtossShieldsLevel2', 
       'player_2_ObserverGraviticBooster', 
       'player_2_GraviticDrive', 
       'player_1_ProtossGroundArmorsLevel1', 
       'player_1_DarkTemplarBlinkUpgrade', 
       'player_2_ProtossGroundArmorsLevel1', 
       'player_1_GraviticDrive', 
       'player_1_ProtossAirWeaponsLevel1', 
       'player_2_AdeptPiercingAttack',
       'player_2_FleetBeacon_live', 'player_2_FleetBeacon_dead', 'player_2_FleetBeacon_in_progress', 
       'player_1_FleetBeacon_live', 'player_1_FleetBeacon_dead', 'player_1_FleetBeacon_in_progress', 
       'player_2_Tempest_live', 'player_2_Tempest_dead', 'player_2_Tempest_in_progress', 
       'player_2_ProtossAirWeaponsLevel1', 
       'player_1_Carrier_live', 'player_1_Carrier_dead', 'player_1_Carrier_in_progress', 
       'player_1_Interceptor_live', 'player_1_Interceptor_dead', 'player_1_Interceptor_in_progress', 
       'player_1_Tempest_live', 'player_1_Tempest_dead', 'player_1_Tempest_in_progress', 
       'player_2_ProtossAirWeaponsLevel2', 
       'player_1_ProtossAirWeaponsLevel2', 
       'player_2_Mothership_live', 
       'player_2_Mothership_dead', 
       'player_2_Mothership_in_progress', 
       'player_2_ProtossAirWeaponsLevel3', 
       'player_2_Carrier_live', 
       'player_2_Carrier_dead', 
       'player_2_Carrier_in_progress', 
       'player_2_Interceptor_live', 
       'player_2_Interceptor_dead', 
       'player_2_Interceptor_in_progress', 
       'player_1_ProtossGroundArmorsLevel2', 
       'player_2_Colossus_live', 'player_2_Colossus_dead', 'player_2_Colossus_in_progress', 
       'player_1_VoidRay_live', 'player_1_VoidRay_dead', 'player_1_VoidRay_in_progress', 
       'player_2_ProtossGroundArmorsLevel2', 
       'player_1_ProtossShieldsLevel2', 
       'player_1_ProtossAirWeaponsLevel3', 
       'player_1_ProtossShieldsLevel3', 
       'player_1_ProtossAirArmorsLevel1', 
       'player_2_VoidRay_live', 'player_2_VoidRay_dead', 'player_2_VoidRay_in_progress', 
       'player_2_ProtossGroundArmorsLevel3', 
       'player_2_PsiStormTech', 'player_1_PsiStormTech', 
       'player_1_Mothership_live', 'player_1_Mothership_dead', 'player_1_Mothership_in_progress', 
       'player_2_ProtossAirArmorsLevel1', 
       'player_1_ProtossAirArmorsLevel2', 
       'player_2_ProtossAirArmorsLevel2', 
       'player_2_ProtossShieldsLevel3', 
       'player_1_ProtossAirArmorsLevel3', 
       'player_2_ProtossAirArmorsLevel3',  
       'player_2_PhoenixRangeUpgrade', 
       'player_1_ExtendedThermalLance', 
       'player_1_ProtossGroundArmorsLevel3', 
       'player_2_ExtendedThermalLance', 
       'player_1_PhoenixRangeUpgrade']